pkg/pb/synthetic_monitoring/checks.pb.go, pkg/pb/synthetic_monitoring/checks.proto
Add documentation to all the messages that don't have them. Also
clarify, extend and reformat some of the existing comments.
=> Add documentation for all messages

scripts/package/package.sh
=> Run apt-get update before trying to install packages

Makefile, cmd/synthetic-monitoring-agent/main.go, cmd/synthetic-monitoring-agent/version.go, internal/checks/checks.go, internal/version/version.go
Reports:
probe ID
probe name
version
commit
buildstamp
=> Add sm_agent_info metric

internal/pkg/loki/loki.go, internal/pkg/prom/prom.go, internal/pusher/pusher.go
If we receive a 401 (Unauthorized) back from Prometheus or Loki, fetch
tenant information again as what we have in the cache might be stale.
If the information is stale, this is going to happen only once, since
the second time around it will succeed. If the information is stale, we
are going to get the same thing again, and we can drop the payload we
have because something *else* is wrong and we have no way of fixing it.
=> Fetch TenantInfo again if authentication fails

go.mod, go.sum, internal/scraper/scraper.go
Ignore the DontFragment setting until we can provide a fix for the BBE
code.
=> Workaround panic in BBE when DontFragment is set

.circleci/config.yml
=> Update CircleCI config to build and deploy tagged commits

.circleci/config.yml
=> build: Fetch git tags in CircleCI

.circleci/config.yml, Makefile, scripts/package/package.sh, scripts/version
Use a single definition of what the version of the package is.
=> build: get version using scripts/version

CHANGELOG.md
=> Release v0.0.5

.drone.jsonnet, scripts/go/go.sum
=> Make sure version comes out clean

README.md, scripts/package/README.md, scripts/package/package.sh
updated scripts readme and linked to Grafana Cloud Docs on running private probe
=> docs: update and add links

README.md, examples/kubernetes/README.md, examples/kubernetes/deployment.yaml, examples/kubernetes/namespace.yaml, examples/kubernetes/secret.yaml
=> Add deployment example for Kubernetes and Docker

go.mod, internal/scraper/scraper.go, internal/scraper/scraper_test.go, internal/scraper/testdata/dns.txt, internal/scraper/testdata/http.txt, internal/scraper/testdata/http_ssl.txt, internal/scraper/testdata/ping.txt, internal/scraper/testdata/tcp.txt, internal/scraper/testdata/tcp_ssl.txt
=> Feature: Implement test to check metric changes

CHANGELOG.md
=> Prepare release v0.0.7

.drone.jsonnet
The visible change that this brings over the configuration to be able to
trigger builds based on tagging.
The less visible change is that it's building using the most recent
release of Go 1.14.
=> Sync .drone.jsonnet with other projects

CHANGELOG.md
=> Prepare v0.0.8

CHANGELOG.md
=> Prepare v0.0.9

CHANGELOG.md
=> Prepare v0.0.10

CHANGELOG.md
=> Prepapre 0.0.12

pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
We are not validating the labels that we are going to apply to the
metrics, and we eventually hit a call to MustRegister that causes the
probes to crash with bad metrics.
Add validation code for labels, that gets called from checks and probes.
This is going to cause the check to be rejected if it makes it to the
probe, but the intention is that it's rejected in the API or the
frontend, where it can be handled more gracefully. The API is going to
inherit this validation.
Also add TestCheckValidate to make sure we are calling these validations
for incoming checks.
Partially fixes #99 (because of required API and frontend fixes).
=> Fix: validate check and probe labels

CHANGELOG.md
=> Release v0.0.13

pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
=> Add HTTP url validation

CHANGELOG.md
=> Release v0.0.14

CODEOWNERS
=> Use @grafana/synthetic-monitoring-dev in CODEOWNERS

CHANGELOG.md
=> Release v0.0.15

CHANGELOG.md
* Pin fpm version to 1.11.0 (#115)
=> Release v0.0.16

CHANGELOG.md
* Fix: typo in client certificate and key
* Add DNS-specific validation
=> Release v0.0.17

pkg/accounting/accounting.go, pkg/accounting/accounting_test.go
In order to make it possible for users of this code to validate that
new variations of check types have been added (or removed), provide
access to a copy of the accounting information via
GetAccountingClassInfo. Also provide access to the "accounting class" of
a check, which is the key used in that map. This makes it possible to
validate whether a check has switched classes if necessary.
=> Feature: provide access to accounting map

CHANGELOG.md
=> Prepare release v0.0.18

.circleci/config.yml, .drone.jsonnet
=> Change references from 'master' to 'main'

README.md
=> Change last reference from `master` to `main`

cmd/synthetic-monitoring-agent/main.go, internal/checks/checks.go
By passing `--features foo,bar,baz` it's possible to indicate that a
particular agent is willing to accept running new features while they
are being developed.
No features have been defined yet.
=> Feature: add a features flag on the command line

scripts/package/publish.sh
First pass at publishing RPM packages.
=> Feature: add support for publishing RPM packages

scripts/release
Add a script capturing the steps necessary to create a release.
=> Feature: add release script

cmd/synthetic-monitoring-agent/main.go
Add -version flag to report the program's version and exit.
=> Feature: report program's version

.drone/README.md, .drone/drone.jsonnet, .drone/drone.yml, Makefile
Builds are currently not running because the signature is out of date
=> Update Drone signature and add README

.drone/drone.jsonnet, .drone/drone.yml, Dockerfile.pub, go.mod
=> Move to Go 1.17

internal/prober/dns/dns_test.go, internal/prober/http/http_test.go, internal/prober/icmp/icmp_test.go, internal/prober/tcp/tcp_test.go, internal/prober/traceroute/traceroute_test.go
A start to some tests for probers, covering `settingsToModule`
=> [cr] baseline tests for settingsToModule for each prober type

internal/checks/checks.go
Add a simple metric to report the status of the connection to the API as
either up or down.
=> Feature: report API connection status

internal/prober/dns/dns_test.go, internal/prober/http/http_test.go, internal/prober/icmp/icmp_test.go, internal/prober/tcp/tcp_test.go, internal/prober/traceroute/traceroute_test.go
Gets coverage for each prober to >90%
=> [cr] test coverage for NewProber for each probe type

internal/checks/checks.go, internal/checks/checks_test.go, internal/scraper/scraper.go
=> Add test for handleCheckOp functions

README.md, examples/kubernetes/README.md, examples/kubernetes/deployment.yaml
links to public docs so we don't have to update docs twice.
=> Centralise and update docs

internal/scraper/scraper.go
This is a minimal change to support adding the log labels to the log
entries themselves.
In the future we would like to remove user-defined labels from the
labels and keep them in the log entries only in order to allow users to
add _more_ labels, but this change is not that.
=> Feature: add log labels to log entries

internal/checks/checks.go
=> Feature: enable traceroute checks by default

internal/scraper/scraper.go, internal/scraper/scraper_test.go, pkg/pb/synthetic_monitoring/checks_extra.go
This should not introduce any behavior changes, but it makes it easier
to add them later.
=> Add test for scraper collectData method

.drone/drone.jsonnet, .drone/drone.yml
=> Fix drone config

internal/pusher/pusher.go
=> Fix: 401 handling seems to be wrong

.drone/drone.jsonnet, .drone/drone.yml
=> Parallelize more steps in the build

cmd/synthetic-monitoring-agent/main.go
=> Fix linter errors

cmd/synthetic-monitoring-agent/main.go, internal/prober/prober.go
I'm sorry, I was experimenting locally, and somehow pushed from the wrong window. This is to back out that change. Should not have had serious impact on anything, as it is mostly unreachable code.
=> Revert Inadvertent Commit

cmd/synthetic-monitoring-agent/main.go
=> Increase GRPC logging level if --debug is passed

Makefile
=> Feature: cross-compile binaries for ARM and ARM64

.drone/drone.jsonnet, .drone/drone.yml
=> Allow for building multiple docker images

Makefile, cmd/test-api/internal/db/db.go, cmd/test-api/internal/grpc/checks.go, cmd/test-api/internal/grpc/grpc.go, cmd/test-api/internal/grpc/grpc_test.go, cmd/test-api/internal/grpc/tenants.go, cmd/test-api/main.go, go.mod, go.sum, pkg/pb/synthetic_monitoring/checks_extra.go
I use this for testing. It's a simple way of passing checks to an agent
without actually having to connect it to an actual API.
What's possibly missing is correct handling of reconnects, etc.
=> An small (and possibly incorrect) implementation of the API

cmd/test-api/internal/db/db_test.go
=> Add tests for cmd/test-api/internal/db

.goreleaser.yaml, Makefile, scripts/goreleaser-build
=> Add goreleaser configuration

internal/prober/k6/k6.go, internal/prober/k6/runner.go
=> Add very simple code to publish k6 metrics and logs

go.mod, go.sum, internal/scraper/testdata/http_ssl.txt, internal/scraper/testdata/http_ssl_basic.txt, internal/scraper/testdata/tcp_ssl.txt, internal/scraper/testdata/tcp_ssl_basic.txt
This includes changes the TLS metrics so that they report more details about the certificates.
=> Update BBE to pre-release commit cc533f125b41

cmd/synthetic-monitoring-agent/main.go, internal/adhoc/adhoc.go
=> Fix: set up backoffer to adhoc handler

scripts/release
=> Display short changelog when release is called without arguments

cmd/synthetic-monitoring-agent/main.go, scripts/package/config/systemd/synthetic-monitoring-agent.conf
=> Fix: default to listening on localhost, not all interfaces

cmd/synthetic-monitoring-agent/http.go, cmd/synthetic-monitoring-agent/main.go
In order to avoid having to restart the agent just to change the log level, add a method (POST to /logger with "debug" or "default") to change the level at runtime.
=> Add method to change log level at runtime

internal/prober/multihttp/script.go, internal/prober/multihttp/script_test.go
- Lowercase header names, headers are case insentive
- Fix header mapping logic
=> Fix header matching

CHANGELOG.md
* Fix: don't use 0 in subject and condition enums
* Chore(deps): Bump github.com/prometheus/client_golang
* Chore(deps): Bump golang.org/x/net from 0.10.0 to 0.12.0
* Chore(deps): Bump github.com/stretchr/testify from 1.8.3 to 1.8.4
* Chore(deps): Bump google.golang.org/grpc from 1.55.0 to 1.56.2
* Chore(deps): Bump golang.org/x/sync from 0.2.0 to 0.3.0
* Update scripts/release
=> Release v0.16.5

internal/prober/multihttp/script.go, internal/prober/multihttp/script.tmpl, internal/prober/multihttp/script_test.go
The body of the HTTP request is being ommited because I forgot to add a TODO item.
=> Fix: pass body to HTTP request if specified

internal/pusher/metrics.go
This will break existing dashboards...
=> Fix label names, it should be "type" not "target"

CHANGELOG.md
* Add jitter to tenant's maxLifetime
=> Release v0.17.3

internal/scraper/scraper.go, internal/scraper/scraper_test.go
This is causing issues with existing dashboards.
I need to figure out a deploy this without causing disruptions.
=> Remove source label from metrics

CHANGELOG.md
* Change scripts/release to handle squashed commits (#540)
* Remove source label from metrics (#541)
=> Release v0.18.1

CHANGELOG.md
* Add methods to convert to and from strings for MultiHTTP enums
=> Release v0.18.2

CHANGELOG.md
* Fix: make sure the String() methods match the proto defintion
=> Release v0.18.3

internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go
The server is expecting a `settings` field.
=> Fix RunRequest definition

CHANGELOG.md
=> Release v0.19.1

cmd/synthetic-monitoring-agent/http.go, internal/http/http.go
Instead of the hacky code interceptor, use httpsnoop to capture information about the requests going to the ops server.
=> Clean up ops observability

CHANGELOG.md
* Clean up ops observability
* Swtich to grafana-build-tools
* Update dependencies
* Add support for gRPC checks (#571)
=> Release v0.19.2

.drone.yml, .goreleaser.yaml, scripts/configs/drone/main.jsonnet
Everything _but_ make release-snapshot is running for PRs. That doesn't make sense.
=> Fix: test release on PRs

CHANGELOG.md
=> Release v0.19.3

CHANGELOG.md
* Chore(deps): Bump google.golang.org/grpc from 1.60.0 to 1.60.1 (#580)
* Chore(deps): Bump github.com/mccutchen/go-httpbin/v2 (#579)
* Chore(deps): Bump github.com/prometheus/client_golang (#582)
* Chore(deps): Bump golang.org/x/sync from 0.5.0 to 0.6.0 (#583)
* Chore(deps): Bump golang.org/x/net from 0.19.0 to 0.20.0
* Chore(deps): Bump github.com/prometheus/common from 0.45.0 to 0.46.0 (#588)
* Chore(deps): Bump github.com/mccutchen/go-httpbin/v2 (#589)
* Chore(deps): Bump github.com/google/uuid from 1.5.0 to 1.6.0 (#591)
* fix: allow scripted checks to have anything as the target value (#592)
* Chore(deps): Bump google.golang.org/grpc from 1.60.1 to 1.61.0 (#593)
* Chore(deps): Bump github.com/prometheus/prometheus from 0.48.1 to 0.49.1 (#594)
=> Release v0.19.4

internal/scraper/scraper.go, internal/scraper/scraper_test.go, pkg/pb/synthetic_monitoring/checks_extra.go
This change allows a check to run less often by storing the produced metrics and pushing the last set that was produced by the scraper once every 2 minutes.
=> Feature: allow checks to run less often

internal/checks/checks.go, internal/checks/checks_test.go, internal/scraper/metrics.go, internal/scraper/scraper.go, internal/scraper/scraper_test.go
The function is becoming too messy. Clean up a little by replacing the counter arguments with a generic metrics interface.
=> Clean up scraper factory

CHANGELOG.md
* Expose agent label constants (#606)
=> Release v0.23.1

CHANGELOG.md
* Log publisher errors (#661)
* Remove max check labels verification (#659)
=> Release v0.23.3

CHANGELOG.md
* Bump Go to 1.22 (#699)
* Fix: report duration from script (#698)
=> Release v0.24.1

internal/k6runner/k6runner_test.go, internal/prober/multihttp/multihttp.go, internal/prober/scripted/scripted.go, internal/scraper/scraper.go
A few comments I've extracted out of #724 for easier reviewability.
=> Formatting, logging, and small test improvements

CHANGELOG.md
* Add browser checks capability (#807)
=> Release v0.25.2

.drone.yml, .gbt.mk, scripts/configs/drone/go-tools-image.libsonnet, scripts/configs/drone/main.jsonnet, scripts/generate-drone-yaml, scripts/make/helpers.mk
It looks like updating the version from the .gbt.mk never worked and the TLA is not actually used.
Add some logic to read the version information from that file.
=> Update grafana-build-tools to 0.23.1

internal/k6runner/k6runner.go
After deploying this, I realized there is no actual indication of retries being performed as all log messages indicating that are sent with Debug level. I think these messages are important to diagnose the health of the system, so this PRs promotes them to Warn or Error levels.
Instead of logging each error before it is returned in `HttpRunner.Run`, it would be better to just returh the error and log it in `Processor.Run`. However that's not currently realistic, as `Processor.Run` does not distinguish HTTP runners from local runners, and it is normal for local runners to return errors (e.g. on non-zero exit codes). Fixing that needs a larger refactor.
=> k6runner: promote log messages surfacing errors to warning level

internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go
With remote k6 runner retries implemented in https://github.com/grafana/synthetic-monitoring-agent/pull/724, we sometimes face a situation where the cure is worse than the disease: The original request that timed out, as well as all retries, start to pile up in the queue, and the runners waste their time running them which further cause them to lag more, creating more timeouts and more retries.
This PR makes a simple change where the time at which the agent will give up on a given request is included in the request itself. Remote runners will take this value, sanitize it, and stamp it in the request queue. When the request is picked up, this value is examined, and if it is already in the past, the request is ignored as the runner can be sure that no one is waiting for it anymore.
=> internal/k6runner: send NotAfter hint

internal/adhoc/adhoc.go
k6-backed checks need some grace time between the check timeout, which is enforced by the runners, and the request timeout, which is the time for which the agent will wait to hear back from the runners. If those numbers are the same, the agent is almost guaranteed to give up on the runner before the latter is able to communicate that a timeout occurred, yielding an unhelpful error message (as the agent does not know what happened).
=> feat: adhoc: add some grace time to k6 check timeouts

internal/k6runner/http_test.go
With the current version it's possible to have a failure because the randomly selected number is already used. That's not just bad luck because the code doesn't try to recover from that.
Allow the OS to do its job, and simply ask what the outcome is. The number is not needed for anything other than letting the client know where to connect to.
=> Fix TestHttpRunnerRun

.github/actionlint.yaml, .github/actions/go-cache-restore/README.md, .github/actions/go-cache-restore/action.yml, .github/actions/go-cache-save/README.md, .github/actions/go-cache-save/action.yml, .github/dependabot.yml, .github/renovate-app.json, .github/renovate-selfhosted.json, .github/renovate.json5, .github/workflows/build_and_publish.yaml, .github/workflows/build_and_publish_main.yaml, .github/workflows/build_and_publish_tag.yaml, .github/workflows/renovate-reviewer.yaml, .github/workflows/renovate-validate.yaml, .github/workflows/renovate.yaml, .github/workflows/validate_pr.yaml, scripts/get-go-cache-key, scripts/list-sh-scripts, scripts/make/helpers.mk, scripts/make/linters.mk, scripts/make/testing.mk, scripts/make/xk6.mk
Copy workflows from sm-alerts, where it's been tested that it's working.
We still need to pull the makefile changes. For now this will run in parallel to the Drone set up.
=> Sync .github contents

.github/workflows/validate_pr.yaml
Add support for building the docker image with and without browser in validate_pr.yaml.
=> Build docker image with browser in validate_pr.yaml, too

.github/workflows/build_and_publish.yaml
The correct values are 'dev' and 'ops', not 'prod'.
=> Fix: change vault_instance to ops

internal/telemetry/region_pusher_test.go
CI is failing consistently with this test. The best I can tell, it might be because some data is shared between tests, and the test might be time-sensitive.
=> Fix: simplify TestTenantPusher

.github/release-please/release-please-config.json
Include `chore` as a supported category for release-please. Chore commits refer to changes that don't modify source files but are necessary to maintain the project. Some examples include:
- Updating build scripts or configuration files
- Updating dependencies
- Updating CI/CD configurations
Consider using scopes in order to "narrow down" the context of the change. For example:
- chore(ci): <change>
- chore(build): <change>
=> chore: Add support for chore commits in release-please

.github/release-please/release-please-config.json
Changing it to lower case to match the agreed convention.
=> chore: Fix release-please commit case

.gbt.mk, .github/workflows/build_and_publish.yaml, .github/workflows/validate_pr.yaml, internal/scraper/testdata/browser.txt, internal/scraper/testdata/browser_basic.txt, internal/scraper/testdata/dns.txt, internal/scraper/testdata/dns_basic.txt, internal/scraper/testdata/grpc.txt, internal/scraper/testdata/grpc_basic.txt, internal/scraper/testdata/grpc_ssl.txt, internal/scraper/testdata/grpc_ssl_basic.txt, internal/scraper/testdata/http.txt, internal/scraper/testdata/http_basic.txt, internal/scraper/testdata/http_ssl.txt, internal/scraper/testdata/http_ssl_basic.txt, internal/scraper/testdata/multihttp.txt, internal/scraper/testdata/multihttp_basic.txt, internal/scraper/testdata/ping.txt, internal/scraper/testdata/ping_basic.txt, internal/scraper/testdata/scripted.txt, internal/scraper/testdata/scripted_basic.txt, internal/scraper/testdata/tcp.txt, internal/scraper/testdata/tcp_basic.txt, internal/scraper/testdata/tcp_ssl.txt, internal/scraper/testdata/tcp_ssl_basic.txt, scripts/make/helpers.mk
This pulls in Go 1.23.5, which contains a couple of security fixes (which shouldn't affect this code).
=> fix: Update grafana-build-tools to v0.37.0

scripts/configs/golangci.yml
https://github.com/grafana/synthetic-monitoring/issues/239
=> chore: golangci: remove properties rejected by schema

internal/adhoc/adhoc.go, internal/adhoc/adhoc_test.go
This is trying to test for possible mistakes in setting up ad-hoc checks in the future.
=> fix: Add a safety net in adhoc's defaultRunnerFactory

go.mod, go.sum
Just ran `go get ...@latest`. Let's see if renovate picks up this pattern.
=> chore: update grafana.com/loki/pkg/push
