pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
Ping, DNS and TCP checks should accept only IP addresses or fully
qualified hostnames as targets.
=> Validate IP addresses / hostnames in targets

go.mod, go.sum, internal/scraper/scraper.go
Fixes crashing of probe becuase of don't fragment option and the
incorrect reporting of content length when using regular expression
validations.
=> Update blackbox_exporter to current master

.drone.jsonnet
This moves all builds from circleCI to drone. On pull request does all lint and build steps.
On push to master it will do all that, as well as publishing docker image and packages.
=> Move build from circleCI to drone

.drone.jsonnet
The version reported by the agent is derived from the tags in the repo.
If we are building in a repo with modified files, the version is going
to be labeled as "dirty".
For reproducibility's sake, fail if the repo is dirty during CI.
=> Fail build if repo is dirty

.chglog/CHANGELOG.tpl.md, .chglog/config.yml
The CHANGELOG.md is generated using git-chglog. Add the corresponding
configuration files to the repository.
git-chglog is found at https://github.com/git-chglog/git-chglog
=> Build: Add git-chglog configuration files

pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
RFC 1123 indicates that it's OK for host names to start with digits, and
there are plently of examples of this out there. Relax the FQHN
validation to accept that.
Modify the tests to accept this change.
=> Fix: be more flexible with what we accept for a FQHN

internal/scraper/scraper.go
updateSummaryFromMetric and updateHistogramFromMetric receive a registry
and maps holding the existing histograms for the scraper. The registry
is created fresh every time this function is called, but the maps are
reused. This means the entries in the maps have to be created once, but
the histograms / summaries have to be registered everytime this runs.
=> Fix: keep registering summaries and histograms

examples/kubernetes/secret.yaml
data requires users to encode data in base64, use stringData to let k8s do base64 encoding
k8s docs: https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-config-file/#create-the-config-file
=> Use stringData instead of data

pkg/pb/synthetic_monitoring/checks.proto
In order to be able to report this information as part of probe listing,
add them to the "Probe" message. This should not be sent when adding
probes, only when listing them.
=> Feature: Add version, commit and buildstamp to Probe

cmd/synthetic-monitoring-agent/main.go
help message for `--api-token` flag is not correct, fix it
=> Update help message for apiToken flag

pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
- Added a test case in check validation where check frequency is grater then max timeout(10 seconds).
- Fixed typo
follow up on https://github.com/grafana/synthetic-monitoring-agent/pull/100
=> Add a test case in check validation & fix typos

pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
DNS records should be hostnames, not IP addresses, and they have their
own rules (e.g. a fully qualified DNS name ends with a full stop, so
something like "google." is a valid query, but "google" isn't).
Allow for querying "localhost" and "localhost.", too.
Closes #75
=> Add DNS-specific validation

internal/scraper/scraper.go
It seems this has been present for ages. Instead of using the client
certificate and key, this code is trying to use the CA certificate for
that purpose.
Fix that.
=> Fix: typo in client certificate and key

cmd/synthetic-monitoring-agent/main.go, internal/pusher/pusher.go, internal/pusher/tenant_manager.go, internal/pusher/tenant_manager_test.go
To avoid spamming the API server with requests for tenant information,
cache it in the agent for a short time. This is also causing the
requests to be queued, since GetTenant is issued with the lock held.
=> Cache and queue tenant requests in the agent

internal/checks/checks.go, internal/scraper/scraper.go, pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
The checktype is determined by the settings field, as exactly one field
can be set. Even so, it's useful to be able to ask for the check type
without reimplementing logic that knows about this quirk.
=> Feature: add method to report check type

Makefile, pkg/accounting/accounting.go, pkg/accounting/accounting_test.go, pkg/accounting/data.go, pkg/accounting/data.go.tmpl, pkg/accounting/generate-active-series-counts, pkg/accounting/generate-active-series-counts.go
Add a function to obtain the number of active series generated by a
check based on its configuration. The number is obtained from the
actual metrics emitted by each check type.
=> Feature: provide number of active series per check type

pkg/accounting/accounting.go, pkg/accounting/accounting_test.go, pkg/pb/synthetic_monitoring/checks_extra.go
In order to make it possible to associate accounting classes with check
types, extend the information returned by GetAccountingClassInfo to
include that detail.
=> Fix: provide check type along with class info

Makefile, scripts/genproto.sh
Call the existing protobuf code generation script from the generate
target of the makefile. Clean up the script so that the make target is
less noisy and the output makes more sense.
=> Add protobuf code generation to generate target

Makefile
Use:
$ make testdata
to update the golden files in internal/scraper/testdata/.
Other future golden files should be generated from the same target.
=> Add target to Makefile to update golden files

Makefile
Copy-paste error: it's `test`, not `go`.
=> Fix testdata target

pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
Currently we allow label names and label values to have a maximum length
of 32 bytes. Increase this to 128. The number is still lower than the
maximum of 2048 allowed by Cortex because the UI becomes harder to use
with really long values.
=> Change: Increase the maximum label length to 128

pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
Validate that user-defined labels are not using duplicated names, e.g.
label_a = 1 and label_a = 2.
Fixes #139
=> Fix: check that there are no duplicate label names

pkg/pb/synthetic_monitoring/checks_extra_test.go
These were left out of 00e563ac538647075a60aee45e1cec746f48a835
accidentally.
=> Fix: Add extra header validation tests

internal/pusher/pusher.go, internal/scraper/scraper.go, internal/scraper/scraper_test.go, internal/version/version.go
The user agent identifies the synthetic monitoring agent version, OS,
architecture, buildstamp and commit hash, and it points to the synthetic
monitoring product page on grafana.com so that people can more easily
identify requests as coming from Synthetic Monitoring.
The more explicit user agent version is also passed to Prometheus so
that it's easier to identify issues.
Closes #142 #117
=> Set user agent in outgoing HTTP requests

internal/feature/feature.go, internal/feature/feature_test.go
You can create a feature.Collection, pass that to flagset.Var, and get a
set of features from the command line. On the command line it
understands a flag passed multiple times with different values or a flag
passed one time with multiple values (separated by commas). E.g.:
my_progam --features foo --features bar
my_progam --features foo,bar
=> Add feature package to implement feature flags

Makefile, scripts/report-test-coverage
Add a script to report the overall test coverage. Call it at the end of
a test run.
=> Feature: report overall test coverage

internal/prober/dns/dns.go, internal/prober/http/http.go, internal/prober/http/http_test.go, internal/prober/icmp/icmp.go, internal/prober/logger/logger.go, internal/prober/prober.go, internal/prober/tcp/tcp.go, internal/scraper/scraper.go, internal/scraper/scraper_test.go, internal/tls/tls.go, pkg/pb/synthetic_monitoring/checks_extra.go
This part of the code has always been very messy. Move the logic around
creating a probe out of the scraper package into its own packages and
add a Prober interface that the different probers have to implement in
order to be able to run them.
=> Rework logic around running probers

scripts/package/config/systemd/synthetic-monitoring-agent.service
Older versions of systemd handle quotes in ExecStart. At some point,
probably because people were doing it, systemd started handling quotes
differently. In particular, what's handling the word-splitting in the
arguments is systemd, not a shell, so it started looking at quotes to
prevent splits from ocurring within them. We don't have that case
because all the arguments should be single words without blanks in them.
=> Remove quotes from ExecStart in .service file

internal/scraper/scraper.go, internal/scraper/scraper_test.go
At some point the implementation changed and dropped the +Inf bucket and
nobody noticed (expect me, because I clearly remember fixing this a
while ago).
Fixes: #196
=> Fix: add +Inf bucket to histograms

.drone/drone.yml
and not when merging to master. As far as I'm aware this has two
benefits:
1. We only publish packages/docker images for other people to use when
we are also using them, so we won't be the last to know when we break
something.
2. We avoid a race condition, where two build/publish processes are
happening concurrently when we tag a new release.
=> Only build/publish when tagging a release

scripts/release
If scripts/release is called without a version argument, it will provide
some suggestions as to what the next version might be, and include some
hints as to when each of them should be used (understanding of semver
rules still required).
=> Provide possible next versions in scripts/release

scripts/package/package.sh
They fixed the bug that caused us to pin to version 1.11.0 (empty if
branch causing a shell syntax error). Pin it to a newer version that
works with whatever changed in ffi.
=> Fix: update fpm to 1.13.1

internal/pusher/pusher.go
`tenant` is logging `metricsRemote` and `eventsRemote`, just log tenantId and stackId.
=> Remove tenant from pusher debug log

scripts/package/config/systemd/synthetic-monitoring-agent.conf, scripts/package/config/systemd/synthetic-monitoring-agent.service
We should have the ability to pass feature flags into agents running in VMs. I _think_ this is all that requires.
=> add features to startup command

README.md, internal/checks/checks.go, internal/checks/checks_test.go
If the agent receives a SIGUSR1 signal, it will disconnect from the API,
but it will continue running checks. This makes it possible for a new
version of the agent to connect to the API. When that happens, it's
possible to kill the running agent (SIGTERM or otherwise).
This should provide for a smoother upgrade process.
=> Feature: disconnect agent from API on signal

README.md, cmd/synthetic-monitoring-agent/http.go, cmd/synthetic-monitoring-agent/http_test.go, cmd/synthetic-monitoring-agent/main.go, examples/kubernetes/deployment.yaml, internal/checks/checks.go
When deplying probes in kubernetes like envirements, we need a way to know if agent process is ready.
probe is considered ready when it is to able connect to SM API. 
You can use `/ready` endpoint to check if probe is ready (was able to connect to SM API).  `/ready` endpoint will return HTTP OK (200) with `ready`  when probe is ready.
**demo:**
https://user-images.githubusercontent.com/9503187/143260060-f49a1def-2884-41da-949f-f1eea1780c11.mp4
=> Feature: add /ready endpoint for readiness probe

Dockerfile, scripts/pre-stop.sh
Add a script to the docker image that sends the USR1 signal to the
running agent. This is meant to be used as the preStop hook in a
kubernetes container.
=> Add pre-stop.sh script to send signal USR1 to agent

internal/scraper/scraper.go
The error metric is not getting updated because the scraper runner is
not reporting the failure as an error as expected. The failure is
correctly reported and recorded in user-visible metrics and logs, but
it's not accounted for in the agent's metrics, so it's possible to see
log entries for the checks entering the PASS state but no logs are
recorded for the FAIL state.
=> Fix: correctly propagate check failure

go.mod, internal/checks/checks.go
Connections to the API are too aggressive. Add a exponential backoff in
base the API is actually rejecting connections.
=> Fix: Add a exponential backoff to reconnections

internal/scraper/scraper.go, internal/scraper/scraper_test.go, pkg/pb/synthetic_monitoring/checks_extra.go
Increase the maximum number of check labels to 10. Since Loki limits the
number of labels to 15, give priority to the internal labels (that are
used to provide some Synthetic Monitoring functionality), to probe
labels and then to check labels. All labels will be included as part of
the log entries themselves, so it's still possible to access them via
LogQL queries.
=> Feature: increase maximum number of user labels

README.md, cmd/synthetic-monitoring-agent/http.go, cmd/synthetic-monitoring-agent/main.go
Add `/disconnect` endpoint to send `SIGUSR1` to process.
This endpoint is useful when you want to instruct agent to disconnect but can't send signals directly.
=> Feature: add `/disconnect` endpoint

internal/checks/checks.go
These errors are not exported, but it's good hygiene.
=> Make errors constants

internal/pkg/prom/prom.go, internal/pusher/pusher.go
We had a temporary fix where we were looking at error string to check if we were getting 401 from server. 
`sm_agent_publisher_push_errors_total` metric is still broken after the temporary fix, and it was reporting `0` as status for all errors.
In this change, I am fixing the status code parsing code, and getting rid of temporary fix.
=> Fix: fix http status code parsing for publish

internal/pusher/pusher.go
Add a new metric to track total failure to push data, this will help us narrow down cases when we are dropping data for a tenant
=> feat: Add a metric for failure to publish data

.gitignore, internal/pkg/loki/loki.go, internal/pkg/prom/prom.go, internal/pkg/prom/prom_test.go, internal/pusher/pusher.go
This PR adds a new metrics to track the number of retries performed when sending metrics to the remote Prometheus instance. 
Because the clients themselves aren't aware of the `TenantID` or if they are sending either metrics or log streams, injected in each client a function to emit the metrics value with the labels already pre-filled. Tried doing it some other way but it wasn't as clean.
Related to: https://github.com/grafana/synthetic-monitoring-agent/issues/192
=> Add metric to track prometheus client retries

.gitignore, scripts/README.md, scripts/agent.yaml.tmpl, scripts/docker_build, scripts/sm-dev
This PR adds some tooling for deploying a newly built image of Synthetic Monitoring agent in a kubernetes cluster.
The configuration needed is minimal:
```
API_TOKEN=<probe authentication code>
SM_API_URL=<synthetic monitoring api url> 
```
Once deployed, the script will create 3 resources:
- Pod with grafana agent running
- Service, to encapsulate pods under a networking abstraction
- Ingress, to make the agent http server accessible from `http://sm-agent.k3d.localhost:9999`
=> Add tooling to configure agent in local k3d cluster

.drone/drone.jsonnet, .drone/drone.yml
gcr.io doesn't seem to be doing the right thing wrt having multiple
images with the same tag but for different architectures. It seems the
solution is to publish multi-architecture images.
Follow-up to 00251623e0781e0f389b9ebecc767b04207f7a6c.
=> Don't publish non-amd64 container images

internal/prober/http/http_test.go, internal/prober/http/testserver/testserver.go, internal/prober/prober_test.go
Ideally we would have a set of tests for the full spectrum of HTTP
options. With the testserver package it's possible to control the
responses from the test itself.
=> Small POC for testing the HTTP prober

pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
We will reject URLs that contain passwords because there are dedicated
fields for configuring these. By including the password in the target,
this ends up being part of the metrics and logs labels.
=> Fix: reject passwords in HTTP urls

pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
According to RFC 2181 DNS entries do not really have restrictions other
than length. This is what allows `_srv._tcp.example.org` to exist as a
DNS record.
=> Fix: relax DNS target validation

Makefile
This adjusts the Makefile to prevent crossbuilding for invalid OS/arch targets. After this, `make build` will create binaries for `linux/arm`, `linux/arm64`, `linux/amd64` and the local platform, if different.
Originally, it would build for all combinations of:
GOOS={current, linux}
GOARCH={current, amd64, arm, arm64}
This could cause the build to fail when run on an OS other than Linux. For example, when run under macOS, it will result in an attempt to build a `darwin/arm` binary, which is not a platform supported by Go:
> go: unsupported GOOS/GOARCH pair darwin/arm
> make: *** [build-go-darwin-arm-github.com/grafana/synthetic-monitoring-agent/cmd/synthetic-monitoring-agent] Error 2
=> build: prevent invalid os/arch combinations

cmd/synthetic-monitoring-agent/grpc.go, internal/checks/checks.go, pkg/pb/synthetic_monitoring/checks_extra.go
Currently, the agent can hang in the event of network failure communicating with the API server.
By enabling keep-alive at the GRPC level, the connection will be periodically tested and a reconnect will be triggered if necessary.
This change makes the application layer "ping" unnecessary.
See https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md and https://github.com/grpc/grpc/blob/master/doc/keepalive.md for the GRPC keep-alive specifics.
=> Enable GRPC keep-alive in connection to API server

.drone/drone.jsonnet, .drone/drone.yml, .gitignore
It failed here: https://drone.grafana.net/grafana/synthetic-monitoring-agent/869
=> Ignore the private key created during the release process

go.mod, go.sum
Pull in a new version of the MTR package to prevent a panic that is occuring inside it.
=> Fix: update MTR package

scripts/package/goreleaser-build
A while back the use of the WANTED_OSES and WANTED_ARCHES variables was removed in favor of buidling a single list using PLATFORMS, which has a default value.
When this was fixed, the scripts/package/goreleaser-build wrapper was broken, and we didn't notice because we didn't do a release. Later we didn't notice because we ourselves use the docker images, which are unaffected by this.
Fix this by passing PLATFORMS in the wrapper.
Fixes: #367
=> Fix: WANTED_OSES / WANTED_ARCHES was removed, use PLATFORMS

cmd/synthetic-monitoring-agent/http.go, cmd/synthetic-monitoring-agent/main.go
This adds a new flag, `-enable-pprof` to expose the HTTP pprof endpoint via the HTTP server, under the `/debug/pprof/` path.
Disabled by default.
=> Add flag to enable HTTP pprof endpoint

cmd/synthetic-monitoring-agent/main.go, scripts/package/config/systemd/synthetic-monitoring-agent.conf, scripts/package/config/systemd/synthetic-monitoring-agent.service
Allow the API token to be obtained from the environment. If it's passed on the command line, that value takes precedence.
Use this mechanism in the shipped systemd service file.
=> Fix: allow getting API token from environment

pkg/pb/synthetic_monitoring/checks_extra.go
This is done to mimic the validation order of regular checks, so both fail in the same way.
=> adhoc: Reorder validation of adhoc checks

internal/checks/checks.go, internal/checks/checks_test.go, internal/pusher/pusher.go, internal/scraper/scraper.go, pkg/pb/pb.go, pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go, pkg/pb/synthetic_monitoring/ids.go, pkg/pb/synthetic_monitoring/ids_test.go
Updates the agent to support checks and tenants that use global IDs (IDs that are valid accross different deployment regions).
This allows the agent to run checks for different regions without risk of collisions.
Signed-off-by: Adrian Serrano <adrisr83@gmail.com>
=> Feature: Support global IDs in checks and tenants

internal/adhoc/adhoc.go
BBE prober expect the timeout to be set in the provided context. Since we are not setting up a timeout (deadline), the DNS (and possible TCP) checks are failing immeadiately without running. HTTP works because no deadline means it runs until it completes.
=> Fix: setup timeout in ad-hoc checks

internal/prober/http/http.go, internal/prober/http/http_test.go
Disables the DNS resolution phase in the agent so that DNS is performed at the HTTP proxy.
This prevents checks to fail when the agent doesn't have DNS access.
Also it will cause dns metrics not to be reported when an HTTP proxy is configured.
=> Fix: do not resolve target in http with proxy

internal/pusher/pusher.go
Having the status code as a separate field makes it easier to work with in Loki.
=> Add status to the log entry for publisher errors

.drone/drone.jsonnet, .drone/drone.yml, README.md
Due to security reasons Drone CI secrets are not exposed when the pull request is from a fork. That is why pipeline steps requiring secrets should be skipped.
=> build: Don't expose drone secrets on PR builds

internal/scraper/scraper.go, internal/scraper/scraper_test.go
We generate some label values, so they are not being subject to the constraints the labels provided by the user are.
In order to prevent the metrics from being dropped by Prometheus because the label values exceed the limit, truncate the values that exceed the limit, and replace the last three bytes by '...' to indicate that truncation took place.
For the specific case of certificates with a really long list of Subject Alternate Names (SAN), they end up in a label. It's a list that looks like `a.example.org,b.example.org,c.example.org`. We _could_ split that list and push each individual value as a separate label value just to avoid hitting the limit. The problem with that approach is that we have seen certificates with over 700+ SANs in the wild, so this strategy would push out 700+ …
=> Fix: truncate long label values

go.mod, go.sum, internal/checks/checks.go, internal/prober/multihttp/multihttp.go, internal/prober/multihttp/multihttp_test.go, internal/prober/multihttp/runner.go, internal/prober/multihttp/script.go, internal/prober/multihttp/script.tmpl, internal/prober/multihttp/script_test.go, pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
This supports the multihttp check type.
This shoud be used in tandem with sm-k6-runner (the address should be specified as a command line option).
=> Add multihttp check type

cmd/synthetic-monitoring-agent/main.go
For now, we need to ignore a missing k6 binary.
=> Disable validating k6 path

cmd/synthetic-monitoring-agent/main.go, internal/prober/prober.go
This is not necessary because k6 checks won't be actually created unless the feature flag is enabled, but to avoid issues, prevent the creation of k6 probers unless the k6 runner is correctly configured.
=> Gate k6 checks on runner being configured

pkg/accounting/accounting.go, pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
This is necessary so that the API can map accounting classes to check types and ther corresponding class.
=> Add missing check class data to ClassInfo struct

internal/prober/multihttp/script.go, internal/prober/multihttp/script.tmpl, internal/prober/multihttp/script_test.go
In order to be able to tell from which check any particular error is coming from, we need to add url and method tags to the checks.
=> Add url and method tags to checks

internal/prober/multihttp/script.go, internal/prober/multihttp/script.tmpl, internal/prober/multihttp/script_test.go, pkg/pb/synthetic_monitoring/checks.pb.go, pkg/pb/synthetic_monitoring/checks.proto, pkg/pb/synthetic_monitoring/checks_extra.go
In order to be able to match specific headers in multiHTTP checks, we use the existing `expression` field to specify the header name to match. Other than this, everything works as before. There's a fallback in place, so that in case we have a check _without_ an expression, it uses the old behavior.
=> Feature: use expression to match specific headers in multiHTTP

Makefile, cmd/synthetic-monitoring-agent/main.go, internal/pkg/prom/prom.go, internal/pkg/prom/prom_test.go, internal/pusher/clients.go, internal/pusher/metrics.go, internal/pusher/metrics_test.go, internal/pusher/tenant_manager.go, internal/pusher/v1/pusher.go, internal/pusher/v2/condition.go, internal/pusher/v2/condition_test.go, internal/pusher/v2/errors.go, internal/pusher/v2/errors_test.go, internal/pusher/v2/options.go, internal/pusher/v2/publisher.go, internal/pusher/v2/queue.go, internal/pusher/v2/queue_test.go, internal/pusher/v2/snappy_concat.go, internal/pusher/v2/snappy_concat_test.go, internal/pusher/v2/tenant_pusher.go, internal/pusher/v2/tenant_pusher_test.go
This adds a new publisher (enable with `--publisher v2` flag):
- Uses a single pusher loop per-tenant and is able to submit the results of multiple check runs on a single request.
- Keeps the check results compressed in memory to reduce the memory impact, specially during network outages.
- Can react to various error conditions like rate-limits or out-of-quota.
- Is configurable in terms of memory use (max queued memory per tenant).
=> feat: Experimental per-tenant batched publisher

cmd/synthetic-monitoring-agent/main.go, internal/tenants/manager.go, internal/tenants/manager_test.go
The intention here is that it should be possible to use the tenant manager in more places than just the pusher, and it should be possible to share the cache.
=> Extract TenantManager out of pusher into its own package

internal/adhoc/adhoc.go, internal/checks/checks.go, internal/checks/checks_test.go, internal/model/model.go, internal/model/model_test.go, internal/prober/prober.go, internal/pusher/clients.go, internal/pusher/pusher.go, internal/pusher/v1/pusher.go, internal/pusher/v2/options.go, internal/pusher/v2/publisher.go, internal/pusher/v2/tenant_pusher.go, internal/pusher/v2/tenant_pusher_test.go, internal/scraper/scraper.go, internal/scraper/scraper_test.go
In order to avoid confusion as to which kind of ID is expected where, introduce a model package that takes a synthetic_monitoring.Check and produces a wrapped one that has the IDs decoded.
Introduce a model.GlobaID type to make it explicit which kind of ID is expected. In the scraper use local IDs, except for the lists of checks, which need to use a global one. In the publisher, use global IDs.
This allows the compiler to flag misuses.
=> Use local IDs in scraper, global IDs in pusher

internal/k6runner/k6runner.go
We should share this set of flags between the agent and the k6-runner.
=> Fix: remove --discard-response-bodies

internal/checks/checks.go, internal/checks/checks_test.go, internal/model/model.go, internal/model/model_test.go, internal/scraper/scraper_test.go
In beadaabb8b8408de166f851125867ad703911d53 I changed the code that handles check and tenant IDs. In dev this is panicing because the check and tenant IDs are inconsistent. Perhaps my expectation that they are consistent is invalid?
=> Fix panic while handling changes

internal/model/model.go
In some cases (e.g. check delete operations) we receive a check that only contains the check ID and nothing else, not even the tenant ID.
Change the code so that we obtain the region ID from the check ID, and ignore the value that comes with the tenant.
=> Fix handling of tenant ID zero

internal/prober/multihttp/script.go, internal/prober/multihttp/script_test.go
We want to have something like:
response.html('body > h1').html()
The current code is using the CSS expression as if it were a predicate.
=> Fix: for CSS selectors, the expression is not a predicate

internal/pusher/metrics.go, internal/pusher/v1/pusher.go
sm_agent_push_failed_total has a type label that indicates the type of failure, not the type of payload that is being pushed. Rename that label to `reason` and add a `type` label that has values `metrics` and `logs`.
=> Fix: add type to failure metrics

CHANGELOG.md
* Feature: keep track of scraper executions on a per-tenant level
* Extract TenantManager out of pusher into its own package
* Use local IDs in scraper, global IDs in pusher
* Fix: remove --discard-response-bodies
* Fix panic while handling changes
* Fix typo
* Fix handling of tenant ID zero
* Fix: for CSS selectors, the expression is not a predicate
* Fix: add type to failure metrics
=> Release v0.17.1

internal/pusher/v2/tenant_pusher.go, internal/pusher/v2/tenant_pusher_test.go
At the point of this call, the counter vector doesn't have a type.
p.options.metrics.FailedCounter.WithLabelValues(pusher.LabelValueTenant).Inc()
=> Fix: handle failed counter correctly

internal/pusher/metrics.go, internal/pusher/metrics_test.go, internal/pusher/v2/publisher.go
InstalledHandlers does not have a type associated with it, it's created before that information is available.
=> InstallerHandlers has no type

CHANGELOG.md
* Fix: handle failed counter correctly
* Chore(deps): Bump google.golang.org/grpc from 1.56.2 to 1.58.1
* Chore(deps): Bump github.com/miekg/dns from 1.1.54 to 1.1.56
* Chore(deps): Bump github.com/rs/zerolog from 1.29.1 to 1.30.0
* Chore(deps): Bump github.com/go-kit/kit from 0.12.0 to 0.13.0
* Chore(deps): Bump github.com/google/uuid from 1.3.0 to 1.3.1
* Chore(deps): Bump github.com/mccutchen/go-httpbin/v2
* Chore(deps): Bump google.golang.org/grpc from 1.58.1 to 1.58.2
* Chore(deps): Bump github.com/rs/zerolog from 1.30.0 to 1.31.0
* Add a gauge to track the number of installed publisher handlers
* Chore(deps): Bump github.com/spf13/afero from 1.9.5 to 1.10.0
* InstallerHandlers has no type
=> Release v0.17.2

internal/pusher/v2/options.go, internal/pusher/v2/tenant_pusher.go
In order to avoid all tenants from trying to refresh at about the same time, add some jitter to the maxLifetime they use. This should spread the updates as time passes.
This has the risk of having some tenants update more often than others, but that should not happen often. It still has the problem that during initialization all tenants are going to be updated at about the same time.
I think the longer term solution is to not to tear down the publisher on a regular basis, but simply update the client its using.
=> Add jitter to tenant's maxLifetime

internal/scraper/scraper.go, internal/scraper/scraper_test.go
This allows us to identify the metrics as coming from Synthetic Monitoring.
=> Add a source label to metrics

.drone.yml, config.mk, go.mod, go.sum, scripts/configs/drone/main.jsonnet
We want 1.21 (and ideally >= 1.21.3)
=> Update Go version used to build agent

scripts/release
When a commit is squashed, Github adds (#nnn) to the subject, and this confuses the release script.
Fix it to handle that situation.
=> Change scripts/release to handle squashed commits

Dockerfile, scripts/dummy-k6.sh, scripts/make/xk6.mk
Add the k6 binary with the sm extension built-in to the generated docker image. This allows users to deploy the agent and enabling multihttp checks.
=> Feature: add k6 to docker image

examples/test-api/README.md, examples/test-api/data.json, examples/test-api/test-api.env
test-api is a minimal API server that the agent can connect to. The implementation does not match the implementation of the actual API server used in product, it's simply enough to allow the agent to connect to it and receive checks and tenant information from it.
=> Add example configuration files for test-api

pkg/pb/synthetic_monitoring/checks_extra.go
Currently scripted checks still need a job/target combo like all the other kinds of checks. Currently the target must be a valid HTTP url, but that really doesn't make sense in context:
There's probably no way around requiring a job/target combo, but we should allow any value the users want to enter
=> allow scripted checks to have anything as the target value

pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
The check target is going to be used as the value of the `instance` label and as such, it must be a valid label value. The current validations for label values only look at the length of the value.
=> Fix: check targets must be valid label values

CHANGELOG.md
* allow adhoc k6 checks with unvalidated targets (#598)
* Fix: check targets must be valid label values
=> Release v0.19.5

pkg/pb/synthetic_monitoring/checks_extra.go
Both Prometheus and Loki have relatiely large values for the maximum length of label values (2048). We limit the legth of the labels we apply to metrics and logs mostly to keep the UI usable. Allow for longer target values, because this is actually in use.
=> Fix: increase max target length

.drone.yml, config.mk, scripts/configs/drone/main.jsonnet
This pulls in Go 1.22.0 and some tool updates.
=> Update to grafana-build-tools v0.6.0

pkg/pb/synthetic_monitoring/checks_extra_test.go
This is a follow up to 8338926b3a8c1232e88a6395fe7d3039606b4e6a.
=> Fix: add test for HTTP check with a long URL

internal/checks/checks_test.go, internal/limits/tenant.go, internal/limits/tenant_test.go, internal/scraper/scraper.go, internal/scraper/scraper_test.go
Modifies the label limits query methods to only accept global IDs, and updates the respective calls from scraper.
=> Fix: global tenant id usage for label limits query

CHANGELOG.md
* Add an option to log multihttp responses (#550)
* Update to grafana-build-tools v0.6.0
* Chore(deps): Bump golang.org/x/net from 0.20.0 to 0.21.0
* Chore(deps): Bump github.com/rs/zerolog from 1.31.0 to 1.32.0
* Chore(deps): Bump github.com/miekg/dns from 1.1.57 to 1.1.58
* Fix: add test for HTTP check with a long URL
* Add tenant label limits (#581)
* Release v0.20.0 (#613)
* Fix global tenant id usage for label limits query
=> Release v0.20.1

cmd/synthetic-monitoring-agent/main.go, internal/adhoc/adhoc.go
This has caused a number of questions recently because the "test" functionality requires the "adhoc" feature to be enabled.
We have had this feature for a long time now and we are actively using it. Make it a permanent feature by removing the checks for whether or not it's enabled. Keep the feature flag in case someone is passing it on the command line to avoid breaking those set ups.
=> Feature: promote adhoc to permanent feature

internal/adhoc/adhoc.go, internal/prober/http/http.go, internal/prober/http/http_test.go, internal/prober/multihttp/multihttp.go, internal/prober/multihttp/multihttp_test.go, internal/prober/multihttp/script_test.go, internal/prober/prober.go, internal/scraper/scraper.go, internal/scraper/scraper_test.go
Addressing https://github.com/grafana/synthetic-monitoring-agent/issues/325.
The goal is to add a header `x-sm-id` with a value `checkId-probeId` so we can identify the owner of a check for anti-abuse purposes. This header gets added to`http.Prober.config`.
Happy to hear any suggestions on how to test this Go code better - testing `NewProber()` from `http_test.go` works to assert the resulting http config directly. but it'd be nicer to have a test server or something so I can add an HTTP check to a test `Updater` and validate the request headers sent.
=> Add header to ease tracking HTTP requests

internal/adhoc/adhoc.go, internal/adhoc/adhoc_test.go
Addresses https://github.com/grafana/synthetic-monitoring-agent/issues/586.
Because it looks like we use `zerolog` for system logging on-instance vs `kitlog` for logs we intend to write to Loki for SM checks, ~~I opt to use `kitlog` here to write the `ad-hoc check done` message for test runs on private probes.~~
Update:
The `go-kit/log`'s JSONLogger is annoying to configure the format for the marshalled JSON on. I see we use it for the `logfmt` format on our Loki publishes - maybe we can find a better logger package that does both well.
Mitigating this issue for now by raising the log level to `warn` so it publishes without `--verbose`, but want to circle back later to change the logger impl and bring it down to `info` again.
=> Send adhoc check done logs to Loki without --verbose

cmd/synthetic-monitoring-agent/main.go, internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go, internal/prober/multihttp/script_test.go, internal/scraper/scraper_test.go
Addresses https://github.com/grafana/synthetic-monitoring-agent/issues/587: makes the blacklist IP range for the K6 runner configurable by flag.
=> Configure blacklist ip range for k6 runner

cmd/synthetic-monitoring-agent/main.go, internal/checks/checks.go, internal/checks/checks_test.go, internal/scraper/scraper.go, internal/scraper/scraper_test.go, internal/telemetry/region_pusher.go, internal/telemetry/region_pusher_test.go, internal/telemetry/telemeter.go, internal/telemetry/telemeter_test.go, internal/telemetry/ticker.go, internal/telemetry/ticker_test.go
This PR adds a telemetry subsystem responsible to collect telemetry data for check executions in the agent.
Currently the telemetry data covers executions and executions duration, and is organized per region, tenant and check class. Each region has an independent goroutine which periodically (by default every 5 min) sends the accumulated telemetry data to the proxy/API.
Updates: grafana/synthetic-monitoring#13
=> Add telemetry

internal/scraper/scraper.go, internal/telemetry/telemeter.go
Telemetry metrics should reference the check region, therefore use the region ID extracted from the global check ID.
=> Fix: telemetry region label

cmd/synthetic-monitoring-agent/main.go
This is a no-op, because this is the default behavior of the checks updater if no scraper factory is provided.
The intention here is to be able to pass alternative scraper factories that modify the behavior of the of the scraper based on e.g. program arguments.
=> Pass a scraper factory from main

pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
Allow the maximum interval between successive check runs to be up to 1 hour. This will break some dashboards, because there are built-in assumptions about the maximum value being 2 minutes. In particular, it's going to be necessary to adjust the value we use for ranges, which is hard-coded to 5 minutes. If we change the queries, we still need to adjust values in Grafana, to prevent sampling values at intervals less than the frequency. This is going to be particularly visible in queries that use `increase`, `rate` and similar functions. Because of that, this is mostly about adding backend support for [issue #318](https://github.com/grafana/synthetic-monitoring-app/issues/318).
=> Experimental: increase max frequency to 1 hour

cmd/synthetic-monitoring-agent/main.go
We have been running with v2 for a long time now, and it seems like it's doing what it was designed to do. Switch the default to v2, while still keeping v1 around. We will retire v1 at some point in the future.
=> Feature: switch to pusher v2 by default

internal/scraper/scraper_test.go, pkg/pb/synthetic_monitoring/checks_extra.go
This PR makes modifications to the agent in order to expose how many max labels are associated for any metric and log for each of the supported probes. For example, how many labels are associated at max for any metric from the ones reported when running an HTTP probe.
This information is required in order to validate that the check labels set from the API will not exceed the particular tenant limits for the metrics and logs backends (e.g.: mimir and loki).
A change in the number of max labels being generated from the agent could potentially make some check exceed the tenant limits, therefore there is a test in place (`TestValidateLabels`) which should alert us to update the values and review the tenant limits and possibly take some actions prior to the release. Other possible strategies …
=> Expose agent label constants

.github/dependabot.yml
Dependabot is currently creating separate bumps for packages that often get updated in steplock, such as
https://github.com/grafana/synthetic-monitoring-agent/pull/662 and https://github.com/grafana/synthetic-monitoring-agent/pull/663. This should instruct dependabot to create a single PR for them.
=> dependabot: group prometheus updates

internal/tenants/manager.go, internal/tenants/manager_test.go
In the case where an entry in the cache was expired, if the data could not be refreshed by requesting it to the API, an error was returned. This implied a blocking behavior for various actions, such as:
- [Check executions](https://www.google.com/url?q=https://github.com/grafana/synthetic-monitoring-agent/blob/8599f14b91658c3766ed0243bf23a77d420c073b/internal/limits/tenant.go%23L41&sa=D&source=docs&ust=1711445883630651&usg=AOvVaw0fdvZjbtsvxcfooEP4ID3Z): If limits could not be verified.
- [Publish events](https://www.google.com/url?q=https://github.com/grafana/synthetic-monitoring-agent/blob/8599f14b91658c3766ed0243bf23a77d420c073b/internal/pusher/v2/tenant_pusher.go%23L96&sa=D&source=docs&ust=1711445883630608&usg=AOvVaw1H3i9mDvDrO9Tlka3tzJSh): If tenant remotes could not be obtained. …
=> Allow returning stale data from tenants cache

CHANGELOG.md
* dependabot: group prometheus updates (#664)
* Chore(deps): Bump the prometheus-go group with 2 updates (#668)
* Allow returning stale data from tenants cache (#665)
* Chore(deps): Bump the prometheus-go group with 2 updates (#669)
* Chore(deps): Bump golang.org/x/net from 0.22.0 to 0.23.0 (#670)
* Chore(deps): Bump golang.org/x/net from 0.23.0 to 0.24.0 (#672)
* Chore(deps): Bump golang.org/x/sync from 0.6.0 to 0.7.0 (#673)
* Update grafana-build-tools to v0.10.0 (#676)
=> Release v0.23.2

internal/pusher/v2/queue.go
We have metrics for the errors, but we are not logging the errors, so some details might be getting lost. Log these errors at the point where we know we won't be retrying anymore.
=> Log publisher errors

pkg/pb/synthetic_monitoring/checks_extra.go
This is a cherry-pick from #606 in order to delay the static labels limit verification removal until this mechanism is in place in the API. Once this static verification is removed from the agent, the limit will be checked in the API in relation with the specific tenant limit.
=> Remove static max check labels verification

CHANGELOG.md
* Feature: upgrade k6 to v0.50.0 (#681)
* Chore(deps): Bump github.com/prometheus/blackbox_exporter
* skip interpolating multihttp variables into the metric names (#683)
* proto fields for scripted check enablement (#674)
* Switch to using buf to manage protobuf code (#641)
=> Release v0.23.4

internal/scraper/scraper.go, internal/scraper/scraper_test.go
We are trying to check three different channels, give priority to the signals that say we should stop.
Also fix a hardcoded value in the test.
=> Fix: TestTickWithOffset sometimes if offset is 0

cmd/synthetic-monitoring-agent/main.go, cmd/synthetic-monitoring-agent/secret.go, cmd/synthetic-monitoring-agent/secret_test.go
When the program is starting up, log the configuration parameters. This helps with debugging and support.
Be careful not to log the API secret.
This is a no-op change, but it's a little noisy becuase of the introduction of the config struct.
=> Log configuration at start up

internal/checks/checks.go, internal/checks/checks_test.go
Part of the new capabilities framework, probes must support features that are expected of them upon connection or else will terminate with an error verbose enough to diagnose the issue.
Un-drafting this, but should merge after the [API changes](https://github.com/grafana/synthetic-monitoring-api/pull/815).
=> Terminate agent if capabilities not supported

internal/checks/checks.go, internal/checks/checks_test.go
The proxy release was outdated, causing it to not propagate the `Probe.Capabilities` field to the agents.
This revealed a miss on checking that the field is present in the agent before validating that the K6 config matches the `Capabilities` requirement. This PR updates the requirement to make sure the field is set or else require K6 by default.
=> Make k6 capability validation nil-safe

pkg/pb/synthetic_monitoring/checks_extra.go
We should be using the same timeout validation logic for adhoc and regular checks.
The downside of this is that adhoc checks with long timeouts might take a long time to run. We can fix this by introducing some observability and figuring out if that's a problem or not.
=> Fix: use uniform timeout validation logic

internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go
Previously, k6 runners used to communicate errors by returning a non-200 status code, and not returning the logs of the execution. mq proxy, in addition to returning non-200 status codes, also includes an error code and description for errors that occur while running the script.
With the introduction of https://github.com/grafana/sm-k6-runner/pull/153, we now report as errors exceptions being thrown on the script, such as trying to access undefined variables, or invocations of `fail()`. In this scenario, users likely expect to see the check reported as a failure, but also to see the logs and metrics produced by it.
This PR changes the error-handling logic, so that the response is always parsed for status code that (should) include it, and the success of the check is calculated by checking …
=> k6runner: handle errors reported by http runners

CHANGELOG.md
* Feature: upgrade k6 to v0.50.0 (#681)
* Chore(deps): Bump github.com/prometheus/blackbox_exporter
* skip interpolating multihttp variables into the metric names (#683)
* proto fields for scripted check enablement (#674)
* Switch to using buf to manage protobuf code (#641)
* Release v0.23.4 (#685)
* Fix: TestTickWithOffset sometimes if offset is 0 (#686)
* Chore(deps): Bump the prometheus-go group with 2 updates
* Chore(deps): Bump github.com/miekg/dns from 1.1.58 to 1.1.59
* Log configuration at start up (#689)
* Feature: automatically set up GOMEMLIMIT (#691)
* Terminate agent if capabilities not supported (#684)
* Make k6 capability validation nil-safe (#692)
* Fix: use uniform timeout validation logic (#693)
* k6runner: handle errors reported by http runners
* k6runner/test: add test …
=> Release v0.24.0

go.mod, scripts/go/go.mod
This has no effect on the released images because those are already using Go 1.21, but it's nice to keep stuff in sync.
=> Bump Go to 1.22

internal/scraper/scraper.go, internal/scraper/scraper_test.go, xk6/sm/output.go
Right now we are reporting the time it takes to run a script, including the time it takes for k6 to actually start running the script, plus all other kinds of overhead.
Modify the sm extension to report the script duration, and report that number as probe_duration_seconds. We are still reporting probe_script_duration_seconds as well. This will get fixed in a future change.
=> Fix: report duration from script

cmd/synthetic-monitoring-agent/main.go, internal/feature/feature.go
Resolves https://github.com/grafana/synthetic-monitoring-agent/issues/556.
We could also consider the issue handled by https://github.com/grafana/synthetic-monitoring-agent/pull/615, but I'm not sure we need to keep these around to let operators know they're obsolete - when would we remove these then?
=> Remove adhoc and traceroute feature flags

internal/checks/checks_test.go
I cannot reproduce the flaky test locally, so let's try things and see what sticks.
---
I think this was it: The 100 nanosecond timer was probably long enough for context cancellation to be picked up before the timer expired in our beefy machines, but not in the handicapped CI runners.
=> checks/test: make timer big enough for context cancel to be picked up

internal/prober/multihttp/script.go, internal/prober/multihttp/script.tmpl, internal/prober/multihttp/script_test.go
Addresses https://github.com/grafana/synthetic-monitoring-agent/issues/637.
Writing `encoding.b64decode(<BODY>)` into the template doesn't let us catch where the user is referencing variables.
We should either:
1. Write the whole string expression (`"literal " +vars['var1']+ " more text " +vars['var2']`) directly into the template, or
2. Add a functional block in the template to take the b64-decoded `$body` and replace any interpolated variables in the template code itself.
For option 1, `buildBody` could likely just return the result of `performVariableExpansion` on the body payload.
Option 2 is probably better practice as the user input won't escape the string; however users who are trying to execute arbitrary code _could_ just leverage scripted checks.
=> Fix: Interpolate variables into MultiHTTP request bodies

cmd/synthetic-monitoring-agent/main.go, internal/feature/feature.go
Allow the `--features` flag to be present when running the agent, but keep it defunct and warn users that it's deprecated.
=> Fix: deprecate --features and warn user

internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go
This PR instructs the HTTP-backed k6 runner (Grafana Cloud) to use the context carrying the script timeout as the request context for HTTP requests made to that k6 runner. An extra second of grace time is added to account for network latency is added to the check timeout.
This fixes a potential deadlock where the agent would wait for the HTTP request to complete forever, even longer than the maximum time the script is allowed to run. This does not occur frequently, but could happen on certain scenarios such as when GC runners are abruptly terminated.
Note that this is a stopgap measure to prevent deadlocks in the agent. Ideally, we should have a separate settings for the time we wait for the runner to respond, and the time that the runner allows k6 to wait for. See details about the …
=> k6runner: use check context for http request

CHANGELOG.md
* Chore(deps): Bump golang.org/x/net from 0.24.0 to 0.25.0
* Chore(deps): Bump the prometheus-go group across 1 directory with 2 updates
* Chore(deps): Bump github.com/mccutchen/go-httpbin/v2
* Update to grafana-build-tools v0.11.0 (#705)
* Remove adhoc and traceroute feature flags. (#707)
* Chore(deps): Bump github.com/KimMachineGun/automemlimit
* checks/test: make timer big enough for context cancel to be picked up
* Fix: Interpolate variables into MultiHTTP request bodies (#713)
* Chore(deps): Bump github.com/prometheus/prometheus (#716)
* Chore(deps): Bump github.com/rs/zerolog from 1.32.0 to 1.33.0
* --- updated-dependencies: - dependency-name: kernel.org/pub/linux/libs/security/libcap/cap   dependency-type: direct:production   update-type: version-update:semver-patch ...
* MultiHttp …
=> Release v0.24.2

internal/checks/checks_test.go, internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go, internal/prober/multihttp/multihttp.go, internal/prober/multihttp/multihttp_test.go, internal/prober/scripted/scripted.go, internal/prober/scripted/scripted_test.go, internal/scraper/scraper_test.go
Before this PR, `MultiHTTP` and `Scripted` `Prober`s created k6 runners using only the raw script data (`[]byte`) as input to the runner. This have worked nicely, as until now runners only required two things to work: The raw script data, and a timeout that was encoded in the context for `Runner.Run()`.
We have seen however a couple scenarios that make me think this is not enough for the near future:
- We want to decouple the context from `Runner.Run()`, a.k.a. the request timeout, from the check timeout that is communicated to the runners. This is needed to properly implement what #715 workarounded.
- We want to make k6 runners aware of some check metadata, for troubleshooting. https://github.com/grafana/sm-k6-runner/pull/191 worked around this using a hash, but it's not ideal.
- We want …
=> Create `k6runner.Script` and make probers aware of it

internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go
Before this PR, `withOpts` checked if the IP denylist at `opts.BlacklistedIP` was empty, and if it was, it didn't override the default value (`10.0.0.0/8`). Unfortunately, this effectively prevented from clearning that default, as specifying `--blocked-nets=""` would cause `opts.BlacklistedIP` to become the empty string, which will not be applied over the default.
To prevent having two defaults (cli flag and in-constructor), with the constructor one being always ignored, this PR gets rid of the constructor default.
The changes here should not cause any functional change, as `blocked-nets` defaults to `10.0.0.0/8` either way in the CLI code: https://github.com/grafana/synthetic-monitoring-agent/blob/7123e22162573d5ff1b83649aca571dd7f0479b9/cmd/synthetic-monitoring-agent/main.go#L80 …
=> k6runner: apply empty IP denylist even if it is empty

CHANGELOG.md
The main user-facing change for this release is a partial fix for #730
---
* Build(deps): Bump github.com/miekg/dns from 1.1.59 to 1.1.61
* k6runner: rename Script to Processor
* create k6runner.Script and make probers aware of it
* scraper: formatting
* prober: log errors returned by k6-backed probes as errors
* k6runner/test: fail if the wrong endpoint is hit
* k6runner: apply empty IP denylist even if it is empty
* k6runner: use non-pointer LocalRunner everywhere
* k6runner: prevent clearing ip denylist when calling WithLogger
=> Release v0.24.3

internal/k6runner/k6runner_test.go, internal/k6runner/testdata/test.log
Doesn't actually fix, but related to https://github.com/grafana/synthetic-monitoring-app/issues/835.
When running a script on a remote runner, roughly two kind of errors can occur:
1. An error occurs reaching the remote runner, meaning that the script could not be scheduled. kan example of this can be network errors reaching our infra.
2. The script was executed, and it returned an error. In this case the runner returns the k6 error log as a part of the response body.
This PR adds tests asserting that those errors in the response body (2) are sent to Loki regardless of the reported `errorCode`.
=> k6runner/test: ensure logs are sent to loki when runner reports user errors

internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go
Another step towards https://github.com/grafana/synthetic-monitoring-app/issues/835.
When https://github.com/grafana/sm-k6-runner/pull/208 is merged, there is a theoretical possibility of the logs and/or metrics returned by the runner to be malformed, for example is k6 is killed while it is writing its output.
This PR adds tests for that case, ensuring that:
- Receiving borked metrics triggers an error
- Receiving borked metrics still causes logs to be sent, and the execution to be marked as failure.
=> k6runner: send logs even if metrics are malformed

scripts/package/config/systemd/synthetic-monitoring-agent.conf
@alexwulf noticed agent installations are using port `4031` to serve `/metrics`.
Our default in the docs ([A](https://grafana.com/docs/grafana-cloud/testing/synthetic-monitoring/set-up/set-up-private-probes/#production-deployments), [B](https://grafana.com/docs/grafana-cloud/testing/synthetic-monitoring/set-up/set-up-private-probes/#troubleshooting-private-probes)) and the code ([ref](https://github.com/grafana/synthetic-monitoring-agent/blob/main/cmd/synthetic-monitoring-agent/main.go#L78)) is `4050`. We should align the config file to this.
=> Correct the listen address to scrape metrics to port 4050

.github/renovate-selfhosted.json, .github/renovate.json5, .github/workflows/renovate.yaml
When selfhosted, renovate requires a separate config file ([ref](https://docs.renovatebot.com/self-hosted-configuration/)). This PR splits out self-hosted options to a different file, and points renovate itself to it. Additionally:
- Migrates repo config to json5 (as it allows comments)
- Simplifies the regex looking for grafana-build-tools container image
- Removes `gitAuthor`, so renovate can rebase PRs created by itself with `platformCommit` (https://github.com/renovatebot/renovate/discussions/29106)
=> Split and fix renovate config

pkg/pb/synthetic_monitoring/checks_extra.go
We were getting `invalid check settings` error message when trying to create a browser check.  I believe it's because we're missed a case in the CheckSettings validation
=> Add CheckSettings validation case for browser

internal/checks/checks.go, internal/error_types/error_types.go, internal/prober/prober.go, internal/prober/prober_test.go, pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
Follow-up-to: 9730c0b7759398e2d8c39d4168b2e662df0f95c0
Follow-up-to: db349fdb64dfd4ddb705c7010d26b4f943892a04
=> Route browser checks to the browser prober

.github/renovate.json5
Go modules that are not versioned create PRs continuously, e.g.:
- https://github.com/grafana/synthetic-monitoring-agent/pull/781
- https://github.com/grafana/synthetic-monitoring-agent/pull/778
This PR throttles digest-type updates to go modules so they only happen one out of two Mondays.
=> ci/renovate: limit gomod digest updates to once every two weeks

Dockerfile, cmd/synthetic-monitoring-agent/main.go
As described in: https://github.com/grafana/support-escalations/issues/11346#issuecomment-2213578649
For non-docker installations, we ship a `sm-k6` binary with the required sm extension that we must use. However, this binary is never looked up, and instead we default to a `k6` binary in the system which may not have the required extension, resulting in obscure failures with exit code 255.
This PR changes the default value to `sm-k6`, and adjusts the Dockerfile so the `k6` binary is copied inside with this name.
https://github.com/grafana/synthetic-monitoring-agent/compare/look-sm-k6-first is an alternative to this, but I'm leaning towards this impl for simplicity.
=> Default to `sm-k6` binary instead of `k6`

internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go
Quick nit found while researching https://github.com/grafana/synthetic-monitoring/issues/55. We were not logging errors encountered while parsing log output.
=> k6runner: log errors encountered by logfmt parser

internal/telemetry/region_pusher_test.go, internal/telemetry/telemeter_test.go, pkg/pb/synthetic_monitoring/checks_extra.go, pkg/pb/synthetic_monitoring/checks_extra_test.go
For the purpose of having some clarity in the data that is made available to users, report the class of the browser check as "browser", not "scripted". This allows us to segment the data when reporting executions.
=> Report browser check's class as browser

.github/renovate.json5
Follow up to #785, it seems that these digests may be updated several times per day. This PR further restricts the regex so renovate works during the night and we see the PRs already fresh in the morning.
00 - 8AM UTC should be outside working hours for both EMEA and NASA.
=> ci/renovate: update gomod digests before 8 AM UTC

cmd/synthetic-monitoring-agent/main.go
The "--feature" syntax is not allowed any longer.
=> Info message for -features suggested deprecated syntax.

internal/k6runner/k6runner.go
Do not error when receiving the new error code introduced in https://github.com/grafana/sm-k6-runner/pull/215
=> k6runner: handle ErrorCodeFailed

go.mod, internal/adhoc/adhoc.go, internal/checks/checks.go, internal/checks/checks_test.go, internal/feature/feature.go, internal/prober/dns/dns.go, internal/prober/dns/dns_test.go, internal/prober/dns/internal/bbe/config/config.go, internal/prober/dns/internal/bbe/prober/dns.go, internal/prober/dns/internal/bbe/prober/utils.go, internal/prober/prober.go, internal/prober/prober_test.go, internal/scraper/scraper.go
Copy the BBE DNS probe code to modify it in order to add retry logic. We can try to upstream this, that's why this is not adding any metrics yet.
This will retry 3 times if there's enough time (at least 15 seconds). No DNS check should actually take more than 5 seconds, so when we see a long timeout, inject the retry logic in there.
=> Add retries to BBE DNS probe

CHANGELOG.md
* ci/renovate: update gomod digests before 8 AM UTC
* Update ghcr.io/grafana/grafana-build-tools Docker tag to v0.16.0 (#800)
* Info message for -features used deprecated syntax. (#801)
* Update golang.org/x/exp digest to 8a7402a (#806)
* k6runner: handle ErrorCodeFailed (#791)
* Add retries to BBE DNS probe (#803)
* Update ghcr.io/grafana/grafana-build-tools Docker tag to v0.17.1 (#808)
* Update github.com/grafana/loki/pkg/push digest to 5a87ccb (#804)
=> Release v0.25.1

internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go
This PR causes a last log line to be submitted to the user's Loki instance when a k6 script did not complete successfully. This is a QoL improvement that should help further debug scripts, explicitly logging things like timeouts, k6 getting killed, etc.
=> k6runner: always log error code and string to user's logger

.github/renovate.json5
`\S+` is too wide of a match. For a line like this:
```
local go_tools_image = 'ghcr.io/grafana/grafana-build-tools:v0.15.0';
```
It would match `v0.15.0';`, which is not a valid version. `[\w-+.]` matches all characters allowed in semver.
=> renovate: fix grafana-build-tools dependency regex

.drone.yml, .gbt.mk, Dockerfile, README.md, scripts/configs/drone/main.jsonnet
Issue: https://github.com/grafana/synthetic-monitoring/issues/71
Adds a 3rd stage to the Dockerfile to build the sm-agent image from an Alpine base, installing `chromium-switshader`.
The Drone CI pipeline is also updated to publish new image versions (tagged `*-with-browser`) corresponding to the new build target:
* `latest-with-browser`
* `<semver-long>-with-browser`
We should probably prevent this from publishing until we have some logic in the agent that can leverage it.
=> Add with-browser Docker image

Dockerfile
Renovate (and hopefully dependabot) understand this syntax and will raise PRs when this image is retagged. This should help us stay on top of package updates and CVEs.
Related to https://github.com/grafana/support-escalations/issues/11749
=> Dockerfile: pin hash of debian:stable-slim image

internal/checks/checks.go, internal/checks/checks_test.go
k6 functionality is required in the agent by default, and is NOT required only in case both, scripted and browser checks, have been disabled for the probe from the API.
Updates: https://github.com/grafana/synthetic-monitoring/issues/116
=> feat: Validate browser capability

.drone.yml, scripts/configs/drone/main.jsonnet
I've confirmed that https://github.com/grafana/synthetic-monitoring-agent/pull/886 publishes two separate docker images which are appropriately tagged for the chromium vs base agent images.
Stop publishing the browser image to GCR now.
=> Stop publishing browser image to GCR

Dockerfile
Issue: https://github.com/grafana/synthetic-monitoring-agent/issues/845
We've expanded the Dockerfile into a multi-stage build to include chromium for a browser-enabled agent on Alpine. This PR migrates the base release to Alpine as well.
Tested locally on Colima using a linux/amd64 VM.
=> Migrate base image from Debian to Alpine

internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go, internal/scraper/scraper.go, internal/scraper/scraper_test.go
This PR implements [agent retries for k6 checks](https://docs.google.com/document/d/1kq5xC4izHyJ9WOonS308J8sE3uDG48c6gj4ZPHsWIx4/edit), which cause the agent to retry run for k6-backed checks (MultiHTTP, Scripted and Browser) if they failed *due to infrastructural reasons*. This pr does **not** cause the agent to retry scripts that were executed but failed, for any reason.
The list of errors that will be retried are "documented in go" in the [`HttpRunner.request` function](https://github.com/grafana/synthetic-monitoring-agent/blob/982ccf9561187abbf2d89ba5c0dc7819503a9e82/internal/k6runner/k6runner.go#L414), and can be identified as when `errRetryable` is returned (joined with another error).
In short, errors that are retried are:
- Errors _making_ a request to the hosted runner: Timeout, …
=> Implement retries for remote k6 runners

internal/prober/icmp/icmp.go, internal/prober/icmp/icmp_impl.go, internal/prober/icmp/icmp_test.go, internal/prober/icmp/utils.go
Add a retry mechanism to the ICMP prober. If the packet count is not set, use 3 packets instead of 1, and require that at least 1 of them gets a response. This should cover most reasonable scenarios where retries are needed.
Note that this will send out 3 packets regardless of whether 1 is already received, so this has an impact on the probe_duration_seconds metric (because the probe takes longer to run).
If the time for an individual packet is important, use `sum(probe_icmp_duration_seconds)` instead. That metric is split by phases, and the `rtt` phase is the average round-trip-time for all the received packets. The other two phases, `setup` and `resolve` only run once.
The resolve part of this also retries, in the event that the DNS server fails to produce a response and there's an …
=> Feature: add retries to ICMP prober

internal/adhoc/adhoc.go, internal/adhoc/adhoc_test.go, internal/checks/checks_test.go, internal/prober/browser/browser.go, internal/prober/dns/dns.go, internal/prober/dns/dns_test.go, internal/prober/grpc/grpc.go, internal/prober/http/http.go, internal/prober/http/http_test.go, internal/prober/icmp/icmp.go, internal/prober/icmp/icmp_impl.go, internal/prober/icmp/icmp_test.go, internal/prober/multihttp/multihttp.go, internal/prober/multihttp/script_test.go, internal/prober/prober.go, internal/prober/scripted/scripted.go, internal/prober/tcp/tcp.go, internal/prober/traceroute/traceroute.go, internal/scraper/scraper.go, internal/scraper/scraper_test.go
Some probers need to override the duration that is reported, mostly because we use probe_duration_seconds as the "latency" of the probe, which isn't exactly correct. `probe_duration_seconds` was meant to be used as the duration of the probe: how long did it take for this probe to run. Capture that value in the logs for debugging purposes, and use `probe_duration_seconds` as if it meant the time it takes the target to produce a response, including *some* setup, but not e.g. the overhead introduced by retries or the time it takes for external programs to spin up.
This is OK to change since these are all internal packages.
=> Fix: allow probers to provide a duration value

.github/renovate.json5, Dockerfile
Closes https://github.com/grafana/synthetic-monitoring-agent/issues/846.
Duplicates what @roobre's done to add a regex manager and a custom datasource, so renovate can update pinned alpine packages.
=> renovate: update pinned alpine packages

internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go
It turns out the inline json tag only works for embedded fields. This caused a extraneous `Script` field to be produced in the JSON output, which caused the proxy to reject it.
=> Fix request payload including `NotAfter`

.drone.yml
With the new release process, a push to main happens pretty much at the same time as the tag generation. Notice that the same naming is used for both workflows. This naming has a suffix that is set executing the ./scripts/version script, which will retrieve the current version with the command:
git describe --dirty --tags --long --always
If this command executed for the push CI is run after the tag is created, it will generate a workflow name that conflicts with the one to be created for the tag, not allowing the tag CI/CD to create its workflow.
The fix adds an extra suffix to the workflow name that identifies the workflow "mode", dev for pushes to main, release for tags.
=> ci: Fix argo workflow name conflict

.drone.yml
Looks like drone builds started to stall after #930 was merged. This updates the signature for the file.
I generated the updated signature by running:
```
drone sign grafana/synthetic-monitoring-agent --save
```
=> fix(drone): Resign .drone.yml file

internal/k6runner/http_test.go, internal/k6runner/k6runner.go
Agent-side of https://github.com/grafana/sm-k6-runner/pull/310. This one should be merged **first**.
=> k6runner: rename error code "user" to "aborted"

.github/actionlint.yaml, .github/workflows/build_and_publish.yaml, .github/workflows/validate_pr.yaml, Dockerfile.browser, Dockerfile.build, Dockerfile.no-browser, scripts/export-docker-image, scripts/extract-image-info
Set up the global git config to disable ownership validation, this is causing more grief than necesary and in this particular use case it doesn't really provide anything. This is possibly a bug in actions/checkout.
Tear shared-workflows/build-push-to-dockerhub appart and replace it with a couple of steps (setup-buildx, build-push-action) in a way that the image created in the buildx context is exported to a tar file, so that we can reuse it in a different job to assemble a single multiarch image together.
Add some intermediate steps that capture the result of building the images and uploads them as build artifacts, so that we can download them in a different job where the actual image is created.
Finally, put the images together and push them to GAR. This requires reworking the …
=> Rework build_and_publish.yaml to handle docker images

internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go, internal/prober/browser/browser.go, internal/prober/browser/browser_test.go, internal/prober/dns/dns.go, internal/prober/dns/dns_test.go, internal/prober/grpc/grpc.go, internal/prober/grpc/grpc_test.go, internal/prober/http/http.go, internal/prober/http/http_test.go, internal/prober/icmp/icmp.go, internal/prober/icmp/icmp_test.go, internal/prober/multihttp/multihttp.go, internal/prober/multihttp/multihttp_test.go, internal/prober/multihttp/script_test.go, internal/prober/prober.go, internal/prober/scripted/scripted.go, internal/prober/scripted/scripted_test.go, internal/prober/tcp/tcp.go, internal/prober/tcp/tcp_test.go, internal/prober/traceroute/traceroute.go, internal/prober/traceroute/traceroute_test.go, internal/scraper/scraper_test.go
Similar approach to https://github.com/grafana/synthetic-monitoring-agent/pull/904, but I chose to make a distinction between pure metadata, that is, data that makes it only to the telemetry and does not take part in any decision making, and actual information that is used for decision making. The latter is strongly typed.
=> k6runner: add check metadata and type to remote runner requests

.github/workflows/renovate.yaml
Update get-vault-secrets-action to the last version to make it work with the new vault instance
=> Update get-vault-secrets action

.drone.yml, .gbt.mk, .github/workflows/build_and_publish.yaml, .github/workflows/validate_pr.yaml, scripts/configs/drone/go-tools-image.libsonnet, scripts/make/helpers.mk, scripts/make/release.mk, scripts/package/chglog.yaml, scripts/package/create-parameters-file, scripts/package/nfpm.yaml.template
Instead of the weird workarounds with goreleaser, just use nfpm to create the packages.
- This doesn't do signing.
- This is not changing how the current release works, only adding targets and using them in the GitHub workflow.
=> Fix: rework package creation

.drone.yml, .gbt.mk, .github/workflows/build_and_publish.yaml, .github/workflows/validate_pr.yaml, scripts/configs/drone/go-tools-image.libsonnet
This includes gomplate, which is needed by the packaging scripts.
=> Upgrade grafana-build-tools to v0.30.0

.github/renovate.json5
Follow-up to #768. I mistakenly thought that renovate would be fine to have `1.2.3@sha256:000` as `currentValue`, but it actually needs to have the sha part as `currentDigest`. This PR should fix that.
=> renovate: fix regex for self-updating

.drone.yml, .gbt.mk, .github/workflows/build_and_publish.yaml, .github/workflows/build_and_publish_tag.yaml, .github/workflows/validate_pr.yaml, scripts/configs/drone/go-tools-image.libsonnet
Use GitHub's command line tool (gh) to add packages to the existing release. The assumption is that the tag was created because there's a matching release.
This feels wrong, because we are creating a release and then later, in a separate workflow, we are adding files to that release, instead of doing it in a single location. From my point of view, the problem is that we are conceptually creating a release which creates a tag instead of the other way around. It's even a little weirder because GitHub does support the concept of "draft release", but release-please doesn't.
Fixes: #956
=> Fix: add packages to release

.github/workflows/renovate.yaml
Most of the renovate runs are [timing out](https://github.com/grafana/synthetic-monitoring-agent/actions/workflows/renovate.yaml)
=> Ci renovate timeout

internal/k6runner/http_test.go, internal/k6runner/k6runner.go
This log line is added right after logs from the script itself, and helps bring some context on why the run was marked as failed. Previously, this did not have a log level, making it grey colored and not standing out a lot in the logs. This PR fixes that by making it `level=error`.
=> fix: k6runner: add level=error to deferred log reporting code from runner

.github/renovate.json5
Otherwise, updates are so frequent they become noise
=> chore: Throttle renovate updates

CHANGELOG.md
Something was left behind when we started using release-please, and this anchor
<a name="v0.28.0"></a>
keeps showing up at the top of the changelog.
Move it to the correct location.
=> Chore: move named anchor in changelog

.github/release-please/release-please-config.json
By default release-please creates a commit that looks like this:
chore(main): release vX.Y.Z
Change this to:
Chore: release vX.Y.Z
because the scope is superflous (this is not a monorepo, we only have one thing that we can release) and using uppercase to start the subject line is good form.
=> Chore: change release commit title

.github/renovate.json5, Dockerfile, Dockerfile.build
Terrible, terrible hack to work around the drift in alpine where amd64 and arm64 have different chromium versions.
=> Fix: use different chromium versions for different architectures

.github/renovate.json5, Dockerfile, Dockerfile.build
The new base image is built at https://github.com/grafana/chromium-swiftshader-alpine, and should allow us to both get chromium updates as PRs, while at the same time being stable so an outdated version does not break builds in the foreseeable future.
=> Base browser image on grafana/chromium-swiftshader-alpine

.drone.yml, .github/workflows/build_and_publish.yaml, scripts/configs/drone/go-tools-image.libsonnet, scripts/configs/drone/main.jsonnet
We have the drone pipeline running in parallel with the GHA one, with the exception of the release step. In order to unblock this, disable triggering the argo workflow in Drone and enable it in GHA. I'm 100% sure this is going to fail without changes on the workflow side, but making those changes first will very likely break the drone pipeline. Start it here, with dev releases, so that we can figure out what else needs changing but keep the prod path enabled in Drone, in case we need to make a release before this is done.
=> Fix: trigger argo release workflow from GHA

.github/workflows/build_and_publish.yaml
The current version is failing because it's talking to the wrong vault instance. The new version is the same one that has been verified to work elsewhere.
=> Fix: pull in newer version of trigger-argo-workflow action

.github/renovate.json5, .github/workflows/renovate-validate.yaml, .github/workflows/renovate.yaml
Similar to https://github.com/grafana/sm-k6-runner/pull/353, leverage action definitions and presets in https://github.com/grafana/sm-renovate to keep repo-specific renovate settings to a minimum.
=> chore: use grafana/sm-renovate shared presets and actions

scripts/version
It's been observed that two different runs of git produce two different values of the short SHA-1 value (which is weird, because this is supposed to be based on the number of objects in the repository). Fix this at 12, because that is longer than what git automatically decides to use.
=> Fix: increase SHA-1 short version length

.github/workflows/build_and_publish.yaml
We are passing the docker "tag", not just the version, and in this case the tag includes information about the flavor of the image, which does not match the version embedded in the binary.
As a footnote, yes, I know the tag is the full thing, not just the bits after `:`, but that's how people refer to this. *shrug*
=> Fix: pass version to argo workflow

.github/release-please/release-please-config.json
From the wonderful world of "we have opinions but we don't document them" comes "we provide a sane default configuration but we don't document it."
When 5c21ba3535a071c6166d45812a4d0e11fb1680fe introduced a configuration file for release please, it replaced a built-in default configuration, which does not consist of the default values but a particular set of hand-picked values, with one where default values suddenly apply. In other words, by having an explicit configuration, all the options for which a value is not supplied use the default value. By *not* having a configuration, a predefined one is used, which is not composed of all the default values for all the options.
I do not have the time to figure out where this default configuration comes from, but I can see that it does one thing …
=> Fix: bump minor, not patch, for features

internal/prober/prober.go, internal/prober/prober_test.go
Makes the linter happy
Fixes a linting error blocking https://github.com/grafana/synthetic-monitoring-agent/pull/1102
=> chore: rename add err prefix to unsupportedCheckType error

cmd/synthetic-monitoring-agent/grpc.go, pkg/pb/synthetic_monitoring/checks_extra.go
This is a first step in increasing the maximum timeout for scripted and brower checks. After further testing with this and once we have higher confidence we aim to increase this to 3 minutes.
Related: https://github.com/grafana/synthetic-monitoring/issues/117
=> fix: increase Scripted and Browser max timeout to 90s

.github/workflows/build_and_publish.yaml
When we switched over to GitHub actions, we inadvertently dropped publishing images to docker hub. Reenable that.
Fixes: #1132
=> fix: Publish images to docker hub

pkg/pb/synthetic_monitoring/checks_extra.go
This is the next step (following https://github.com/grafana/synthetic-monitoring-agent/pull/1136) in increasing the maximum timeout for scripted and browser checks. After further testing with this and once we have higher confidence we aim to increase this to 3 minutes.
Related: https://github.com/grafana/synthetic-monitoring/issues/117
=> fix: increase Scripted and Browser max timeout to 120s (#1136)

internal/k6runner/error.go, internal/k6runner/error_test.go, internal/k6runner/k6runner.go, internal/k6runner/local.go
Closes #1060
This pull requests brings a number of improvements to how the local k6 runner, mostly used in private probe context, handles errors from k6. Most prominently:
- For errors that we can attribute to the script contents (user errors), it no longer returns `nil, err` (understood as "k6 could not be run"), but rather a response with a textual representation of the error, and the k6 output. This still causes the test to be marked as failed, but the error is reported to Loki and thus made visible.
- Logs are now parsed and searched for specific strings that, in SM context, are considered fatal errors.
- Limits are imposed on how many bytes will be read for log and metrics output. These are last-resort measures to prevent the whole payload to be rejected by mimir or loki if it is too …
=> feat: k6runner: improve error handling for k6 output

.github/workflows/build_and_publish.yaml
At one point we tagged images with the bare version. For example [v0.29.10](https://hub.docker.com/layers/grafana/synthetic-monitoring-agent/v0.29.10/images/sha256-ddad54c24c4a22cb18169d3e8a52e5a38bf8ac94d21c7e0276f87c5c25fc3372). In the move from drone to github actions this has changed. The latest release has the version [v0.32.0-0-gc17d85830691](https://hub.docker.com/layers/grafana/synthetic-monitoring-agent/v0.32.0-0-gc17d85830691/images/sha256-b55df3b4394dd44a9ae7f28163fb475c922a7f94ae2833cc03641294dde24c8c).
Tools like renovate ignore these tags and thus my images have not been updated since v0.29.10. This PR adds the bare version back, which should make it easier for users to keep up with the latest.
=> fix: tag images with the bare version.

.github/workflows/build_and_publish.yaml, .github/workflows/renovate-validate.yaml, .github/workflows/renovate.yaml, .github/workflows/validate_pr.yaml
The GitHub checkout action has this `persist-credentials` setting.
It's described like this:
persist-credentials: ''
Sounds harmless, right? It almosts makes it sound as if it's going to modify `~/.gitconfig`.
This default of `true` causes credentials to end up in the working copy's `.git/config`, which interacts badly with other stuff happening in GHA.
Set it to false just in case.
=> fix: Use the recommended 'persist-credentials: false' setting

.github/workflows/build_and_publish.yaml
This was missing from https://github.com/grafana/synthetic-monitoring-agent/pull/1166 which tagged only the images uploaded to GHA. It should have also tagged images on docker.
=> fix: tag docker images with the bare version

internal/k6runner/local.go
fix: k6runner/local: disable k6 api server
k6 includes a REST API, enabled by default on localhost, that allows querying it about the state of the test, among other things: https://grafana.com/docs/k6/latest/misc/k6-rest-api/
In SM context, we do not really care about this, and having this enabled will cause k6 to emit a warning if there is another k6 check running, as the second one will fail to bind the same address (`localhost:6565`).
This commit disables the REST API.
=> fix: k6runner/local: disable k6 api server

Dockerfile, Dockerfile.browser, Dockerfile.build, Dockerfile.no-browser
Closes https://github.com/grafana/synthetic-monitoring-agent/issues/847
This might be a little naive, please keep me honest. cc @mem @nadiamoe 
**Looking for feedback on the following**
* ~~Confirm: version this as a breaking change?~~
* Can we make this more restrictive?
* ~~Q about k8s `securityContext` at the bottom of this description.~~
\
**Summary:**
* Sets up a non-root user for both the `release` and `with-browser` build targets of the Dockerfile.
* Updates the `scratch`/tarball-based images to do the same.
* Tested every protocol check config I could attempt (IPv4, IPv6, DNS, traceroute, etc.)
* Tested scripted and browser checks, seem to work.
* Tested on Docker directly as well as K8s.
Here's the toy YAML that I used to run this in my local cluster:
```
apiVersion: v1
kind: Pod …
```
=> Run agent + chromium as non-root user

Dockerfile, Dockerfile.browser, Dockerfile.build, Dockerfile.no-browser
Reverts grafana/synthetic-monitoring-agent#965
Reverting for 2 reasons:
1. The `adduser` command is present in the scratch image, which does not have it -- so CI is [failing](https://github.com/grafana/synthetic-monitoring-agent/actions/runs/13181320850/job/36793682246).
2. The commit message was not taken from the first commit, so `feat:` is missing. This impacts versioning.
I will un-revert this after it merges and fix both the commit message and the scratch image.
=> chore: Revert "Run agent + chromium as non-root user"

Dockerfile, Dockerfile.browser, Dockerfile.build, Dockerfile.no-browser
Reverts grafana/synthetic-monitoring-agent#1186.
Un-reverts grafana/synthetic-monitoring-agent#965.
Original PR is here: https://github.com/grafana/synthetic-monitoring-agent/pull/965.
Diff to fix the scratch image begins at commit 2.
=> feat: Run agent + chromium as non-root user

pkg/pb/synthetic_monitoring/checks_extra.go
This is the final step (following https://github.com/grafana/synthetic-monitoring-agent/pull/1160) in increasing the maximum timeout for scripted and browser checks. Increasing the maximum timeout to 3 minutes.
Related: https://github.com/grafana/synthetic-monitoring/issues/117
=> fix: increase Scripted and Browser max timeout to 180s

scripts/configs/golangci.yml
This linter is disabled, declaring it causes golangci-lint to emit an error and exit with status 7
```
level=error msg="[linters_context] exportloopref: This linter is fully
inactivated: it will not produce any reports."
```
Fixes https://github.com/grafana/synthetic-monitoring-agent/pull/1200 https://github.com/grafana/synthetic-monitoring-agent/pull/1190
=> chore: golangcilint: disable `exportloopref` linter

pkg/pb/synthetic_monitoring/checks_extra.go
It is easy to [make a mistake when editing this](https://github.com/grafana/synthetic-monitoring-agent/pull/1136#pullrequestreview-2546633589). This change should improve readability and help prevent errors.
=> refactor: use time durations in checks_extra for easier readability

cmd/version/version.go, go.mod, internal/version/version.go, internal/version/version_test.go, scripts/make/build.mk, scripts/version
Go 1.24 added a way to obtain the version (extract from the current Git repo) from the running program. Switch to that instead of passing linker flags at build time.
=> fix: Update version reporting logic

Dockerfile, Dockerfile.build, scripts/make/sm-k6.mk, scripts/package/nfpm.yaml.template
~~This depends on https://github.com/grafana/xk6-sm/pull/75/ and therefore the release: https://github.com/grafana/xk6-sm/pull/74~~
To support secrets in the short term we need to add a second k6 binary which tracks the upstream secrets work. This means it is an unreleased k6 version.
This binary will only be used when secret source configuration is provided from the API. This will start to happen with https://github.com/grafana/synthetic-monitoring-agent/pull/1179
=> feat: Add the sm-k6-gsm binary for secrets

cmd/synthetic-monitoring-agent/main.go, internal/adhoc/adhoc.go, internal/checks/checks.go, internal/checks/checks_test.go, internal/k6runner/k6runner.go, internal/k6runner/local.go, internal/k6runner/local_test.go, internal/prober/browser/browser.go, internal/prober/browser/browser_test.go, internal/prober/multihttp/multihttp.go, internal/prober/multihttp/multihttp_test.go, internal/prober/multihttp/script_test.go, internal/prober/prober.go, internal/prober/prober_test.go, internal/prober/scripted/scripted.go, internal/prober/scripted/scripted_test.go, internal/scraper/scraper.go, internal/scraper/scraper_test.go, internal/secrets/tenant.go, internal/secrets/tenant_test.go, pkg/pb/synthetic_monitoring/checks.proto
This change uses the new protobuf fields from https://github.com/grafana/synthetic-monitoring-agent/pull/1192 and passes them down to the k6 executable.
This change requires quite a bit of plumbing to get the details in the right place.
It also includes a small refactor of local.go to make it easier to test the construction of the CLI args.
=> Pass secret store from API

examples/kubernetes/deployment.yaml
Updating the example deployment file so it is consistent with the requirements after https://github.com/grafana/synthetic-monitoring-agent/pull/1187
=> chore: examples/kubernetes: default to a hardened `securityContext`

internal/prober/browser/browser.go, internal/prober/browser/browser_test.go, internal/prober/multihttp/multihttp.go, internal/prober/multihttp/multihttp_test.go, internal/prober/prober_test.go, internal/prober/scripted/scripted.go, internal/prober/scripted/scripted_test.go, internal/scraper/scraper_test.go, internal/secrets/tenant.go, internal/secrets/tenant_test.go
We have several places that need a global tenant ID. We usually communicate this by using models.GlobalTenantID instead of just int64, but the GetTenant function takes a structure that doesn't make a distinction, because it would require updating the protocol buffer definition in a way that would be hard to handle.
Fix the various locations that are using a local ID instead of a global ID.
=> fix: Use a global tenant ID when retrieving secrets information

internal/secrets/tenant.go
Add some logging to GetSecretCredentials in order to make it easier to figure out if there's an issue retrieving secrets.
=> fix: Report errors when retrieving secrets

cmd/synthetic-monitoring-agent/main.go, internal/k6runner/http.go, internal/k6runner/http_test.go, internal/k6runner/k6runner.go
In certain environments, the sm-agent delegates running k6 scripts to a remote runner, through an HTTP API. Requests to this API are subject to retries, and the success rate of requests and the number of attempts they took are key metrics to measure the healthiness of the system.
This PR adds two metrics:
- `requests_total` is a counter that keeps track of each individual HTTP request made. Both the first and subsequent attempts to run a script increment this counter. Labels `success` and `retriable` can be used to see how many requests where successful, and how many errors were retriable. Note that `retriable="1"` does not necessarily mean the request was retried.
- `requests_per_run` is a histogram that keeps track of the number of individual HTTP requests that were made for a given …
=> feat: report metrics about requests made to remote runners

scripts/make/go.mk
`go list -m -f '{{.GoVersion}}'` works for standalone modules, but it doesn't work in a Go workspace. In the later case, the command reports the Go version of _all_ modules in the workspace.
`go mod edit -json` on the other hand only reports the versin in the current module. Having to depend on jq like this is not ideal...
=> fix: Update Go version retrieval logic

scripts/make/testing.mk
This is not changing anything, simply allowing for the possibility to configure the test reporting style. This is helpful if you are making a change where many tests start to fail at once.
=> fix: Make test reporting style configurable

examples/kubernetes/deployment.yaml
For some types of checks, such as HTTP checks with a custom certificate, the agent needs to be able to write the certificate to a temporary path.
The `emptyDir` volume mounted on `/tmp` makes this possible while keeping `readOnlyRootFilesystem: true`.
=> chore: examples: mount an emptydir volume in /tmp

cmd/synthetic-monitoring-agent/main.go, internal/adhoc/adhoc_test.go, internal/checks/checks_test.go, internal/k6runner/http.go, internal/k6runner/http_test.go, internal/k6runner/k6runner.go, internal/k6runner/k6runner_test.go, internal/k6runner/local.go, internal/k6runner/local_test.go, internal/prober/browser/browser.go, internal/prober/browser/browser_test.go, internal/prober/multihttp/multihttp.go, internal/prober/multihttp/multihttp_test.go, internal/prober/scripted/scripted.go, internal/prober/scripted/scripted_test.go, internal/scraper/scraper_test.go, internal/tenants/manager.go, internal/tenants/manager_test.go
In the current version of the code, the secret store is populated when the prober is created. The problem with that is that the prober is created *once* in the lifetime of the check, but the secret store needs to be updated more or less on a continuous basis (because it contains the token used to access the secrets).
=> fix: Change how the secret store is handled

Dockerfile, Dockerfile.build, internal/k6runner/local.go, scripts/make/sm-k6.mk, scripts/package/nfpm.yaml.template
Now that we have a more recent k6 version in xk6-sm[1] we can consolidate
[1]: https://github.com/grafana/xk6-sm/pull/106
=> fix: Remove second k6 binary

internal/tenants/manager.go, internal/tenants/manager_test.go, pkg/pb/synthetic_monitoring/checks_extra.go
This is https://github.com/grafana/synthetic-monitoring-agent/pull/1279 but it also subtracts the max timeout, so that we don't keep trying to use a token beyond its expiry.
=> fix: Bust cache on expiry minus timeout

.github/workflows/build_and_publish.yaml
Updates push-to-gar-docker to v0.4.1 to make it able to use Direct Workload Identity Federation, so no service account should be needed for this repository.
**NOTE**: `v1.0.0` never existed, looks like an arbitrary version.
Part of: https://github.com/grafana/deployment_tools/issues/259653
=>  chore: update push-to-gar-docker action to v0.4.1

examples/kubernetes/deployment.yaml
The `-browser` images need to be able to write temporary data to the home directory.
=> fix: deployment: add commented-out mountpoint for `/home/sm` (browser)

.github/workflows/build_and_publish.yaml
The actual version is already SHA pinned, but the comment will cause renovate to create PRs saying "Update to vX.Y.Z" instead of "Update to abcdef123456".
So this is a no-op aesthetic change.
=> chore: ci: pin exact version of actions/github-create-app-token

internal/k6runner/http.go
Fixes a linting issue surfaced by
https://github.com/grafana/synthetic-monitoring-agent/pull/1190
=> chore: k6runner: replace exp/rand with math/rand/v2

internal/pusher/v2/errors.go, internal/pusher/v2/errors_test.go, internal/pusher/v2/queue.go, internal/pusher/v2/queue_test.go
Right now we are stopping the publisher if we hit Loki's stream limit, as we consider that to be a fatal error. The actual observed behavior is that Loki will accept *some* data and it will reject some. Even more confusing, it seems like the stream was rejected (presumably the one that is going over the limit), might be accepted at a later point in time.
After this change the behavior is that whatever data was rejected is dropped, and the rest of the publisher keeps working as if nothing had happened. We will have to observe the actual behavior to decide if this makes sense or not.
This is related to #1355.
=> fix: Don't stop publisher if we hit Loki's stream limit

cmd/synthetic-monitoring-agent/main.go, internal/checks/checks.go, internal/usage/usage.go, internal/usage/usage_test.go, tmp/build-errors.log
Implement usage report client that can send reports to https://stats.grafana.net/. See https://github.com/grafana/usage-stats/ and https://github.com/grafana/usage-stats-handler/ for backend details about the stats endpoint.
Updates `checks.go` to submit a report whenever a probe is registered or updated. The following metadata is sent over
- Version
- Arch
- OS
- Features
- Public bool
- TenantID
These are the fields that implemented as columns in usage stats(https://github.com/grafana/usage-stats/pull/55). Any other fields that we add to the Report struct will be included as raw json and stored in a `report` field in BigQuery.
Added a flag `disable-usage-reports` which is initially set to true. This provides a buffer so that we can announce that Grafana Labs will start to collect usage …
=> feat: Implement usage report client

.github/workflows/build_and_publish.yaml
Saving 3m from our CI/CD pipeline.
=> chore: ci: do not push browser image to GAR

internal/k6runner/http.go
I've been writing code for 16 years at the time of this commit point but apparently I'm still capable of forgetting to increment a counter in a loop.
=> fix: k6runner/http: increase number of attempts recorded in metric

cmd/synthetic-monitoring-agent/main.go
For nearly all users, the port needs to be specified and needs to be `443`. If skipped, GRPC will fall back to a different port that may not respond to SYN TCP segments. As a result, the agent process will just hang without logging anything.
This change causes the agent to error out if the port is omitted, which allegedly should provide earlier feedback about this and other common mistakes.
=> fix: error out early if grpc address doesn't have a port

internal/limits/tenant_test.go, pkg/pb/synthetic_monitoring/checks_extra.go
This was updated to a default of `22` a while ago - update the constant to reflect that.
=> fix: Update the metrics labels limit const

internal/k6runner/http.go
Quick ad-hoc alternative to https://github.com/grafana/synthetic-monitoring-agent/pull/1443, https://github.com/grafana/synthetic-monitoring-agent/pull/1444.
=> chore: k6/http: log checkInfo when when retries are exhausted

cmd/synthetic-monitoring-agent/main.go
Closes https://github.com/grafana/synthetic-monitoring-agent/issues/586
Lowers the default severity level of logs which are outputted by the application to Warn from Error.
This includes warning logs as a default item of interest for operators, and addresses an issue with adhoc checks on private probes wherein the success message is not published to Loki due to its log level.
=> fix: Change default logging level to WarnLevel

internal/tenants/manager.go
Add a log line if we receive tenants without secret store. This will help identify any issues related to missing secret configuration.
=> fix: add warning when tenant received without secret store details
